### ISSUE TITLE
TypeError: exceptions must derive from BaseException (help me with this)

### ISSUE THREAD

**Issue by Lutom23** [OpenTalker/SadTalker#257]
Traceback (most recent call last):
  File "E:\SadTalker-main\venv\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\SadTalker-main\venv\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "E:\SadTalker-main\venv\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\SadTalker-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\SadTalker-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\SadTalker-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\SadTalker-main\src\gradio_demo.py", line 111, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
  File "E:\SadTalker-main\src\utils\preprocess.py", line 101, in generate
    x_full_frames, crop, quad = self.croper.crop(x_full_frames, still=True, xsize=512)
  File "E:\SadTalker-main\src\utils\croper.py", line 170, in crop
    raise 'can not detect the landmark from source image'
TypeError: exceptions must derive from BaseException

**Comment by magejosh** [comment]
Same problem on my end. Weirdest part is it works sometimes, but others it throws this error right after the point where it renders the temp png, like step 4 based on console output. I'm on a lower end system so I'm of a suspicion it's related to a timeout of some sort but unsure how to test that or fix it.

**Comment by vinthony** [comment]
are you trying a different image? it seems the image does not contain a real face image.

**Comment by keetruda69** [comment]
is there any workaround how to apply model into animated character (not real human face)?

**Comment by ericmday** [comment]
anyone find an answer to this one?

**Comment by KiteA2022** [comment]
anyone find an answer to this one?

**Comment by BeyondYourself** [comment]
Are U OK?

**Comment by jelly-liu** [comment]
change another image, Realistic version, not too much cartoon.

**Comment by keetruda69** [comment]
I found out that image have to have enough facial landmarks in order to get pass through the face detection and trigger swap.

adding facial landmarks is more art or trial-and-error e.g. via SD1.5 inpainting.
