### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by EKI-INDRADI** [OpenTalker/SadTalker#264]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "V:\STABLE_DIFFUSION\SadTalker-main\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "V:\STABLE_DIFFUSION\SadTalker-main\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "V:\STABLE_DIFFUSION\SadTalker-main\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "V:\STABLE_DIFFUSION\SadTalker-main\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "V:\STABLE_DIFFUSION\SadTalker-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "V:\STABLE_DIFFUSION\SadTalker-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "V:\STABLE_DIFFUSION\SadTalker-main\src\gradio_demo.py", line 65, in test
    self.audio_to_coeff = Audio2Coeff(self.audio2pose_checkpoint, self.audio2pose_yaml_path,
  File "V:\STABLE_DIFFUSION\SadTalker-main\src\test_audio2coeff.py", line 43, in __init__
    raise Exception("Failed in loading audio2pose_checkpoint")
Exception: Failed in loading audio2pose_checkpoint

**Comment by vinthony** [comment]
This error does not influence the generation, but i will try to avoid.
