### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by myrainbowandsky** [OpenTalker/SadTalker#269]
系统：Ubuntu22.04，GPU
使用SD插件模式，png图， wav音频
点击生成报错。
ST版本：最新
我看了类似问题1: https://github.com/OpenTalker/SadTalker/issues/249，
但不知道如何解决

```
    Error verifying pickled file from /home/lawrencexu/stable-diffusion-webui/extensions/SadTalker/checkpoints/wav2lip.pth:
Traceback (most recent call last):
  File "/home/lawrencexu/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/home/lawrencexu/anaconda3/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/home/lawrencexu/anaconda3/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lawrencexu/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/home/lawrencexu/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
EOFError: Ran out of input


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.


Traceback (most recent call last):
  File "/home/lawrencexu/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/lawrencexu/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/lawrencexu/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/lawrencexu/stable-diffusion-webui/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/lawrencexu/stable-diffusion-webui/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/lawrencexu/stable-diffusion-webui/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/lawrencexu/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/home/lawrencexu/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 65, in test
    self.audio_to_coeff = Audio2Coeff(self.audio2pose_checkpoint, self.audio2pose_yaml_path,
  File "/home/lawrencexu/stable-diffusion-webui/extensions/SadTalker/src/test_audio2coeff.py", line 35, in __init__
    self.audio2pose_model = Audio2Pose(cfg_pose, wav2lip_checkpoint, device=device)
  File "/home/lawrencexu/stable-diffusion-webui/extensions/SadTalker/src/audio2pose_models/audio2pose.py", line 15, in __init__
    self.audio_encoder = AudioEncoder(wav2lip_checkpoint, device)
  File "/home/lawrencexu/stable-diffusion-webui/extensions/SadTalker/src/audio2pose_models/audio_encoder.py", line 45, in __init__
    wav2lip_state_dict = torch.load(wav2lip_checkpoint, map_location=torch.device(device))['state_dict']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vinthony** [comment]
这个文件有问题，可以试试重新下载：/home/lawrencexu/stable-diffusion-webui/extensions/SadTalker/checkpoints/wav2lip.pth

**Comment by myrainbowandsky** [comment]
在`/path-to-stablle-diffusion-webui/extensions/SadTalker/checkpoints/`执行:
```
wget https://github.com/Winfredy/SadTalker/releases/download/v0.0.2/facevid2vid_00189-model.pth.tar
wget https://github.com/Winfredy/SadTalker/releases/download/v0.0.2/wav2lip.pth

解决
```
