### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'gfpgan'

### ISSUE THREAD

**Issue by Skywalker-Harrison** [OpenTalker/SadTalker#272]
Hi, I have the following error, can you help me solve it?

(sadtalker) XXXXX@alt:~/XXX/XXX/XXX$ python inference.py --driven_audio <$audio_path> --source_image <$pic_path> --enhancer gfpgan
landmark Det:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:16<00:00, 16.43s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  2.09it/s]
Traceback (most recent call last):
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 177, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 210, in __soundfile_load
    context = sf.SoundFile(path)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'gfpgan': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 99, in main
    batch = get_data(first_coeff_path, audio_path, device, ref_eyeblink_coeff_path, still=args.still)
  File "/home/jhliang/Courses/Emo_Computing/SadTalker/src/generate_batch.py", line 59, in get_data
    wav = audio.load_wav(audio_path, 16000) 
  File "/home/jhliang/Courses/Emo_Computing/SadTalker/src/utils/audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 185, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/util/decorators.py", line 60, in __wrapper
    return func(*args, **kwargs)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 242, in __audioread_load
    reader = audioread.audio_open(path)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'gfpgan'
(sadtalker) jhliang@alt:~/Courses/Emo_Computing/SadTalker$ python inference.py --driven_audio <$audio_path> --source_image <$pic_path> --enhancer gfpgan
landmark Det:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:15<00:00, 15.30s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Traceback (most recent call last):
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 177, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 210, in __soundfile_load
    context = sf.SoundFile(path)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'gfpgan': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 99, in main
    batch = get_data(first_coeff_path, audio_path, device, ref_eyeblink_coeff_path, still=args.still)
  File "/home/jhliang/Courses/Emo_Computing/SadTalker/src/generate_batch.py", line 59, in get_data
    wav = audio.load_wav(audio_path, 16000) 
  File "/home/jhliang/Courses/Emo_Computing/SadTalker/src/utils/audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 185, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/util/decorators.py", line 60, in __wrapper
    return func(*args, **kwargs)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/librosa/core/audio.py", line 242, in __audioread_load
    reader = audioread.audio_open(path)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/home/jhliang/miniconda3/envs/sadtalker/lib/python3.8/site-packages/audioread/rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'gfpgan'

**Comment by vinthony** [comment]
you need to give the accurate audio and image path，like xxx.mp3 not <$audio_path>

**Comment by Skywalker-Harrison** [comment]
Oh, I see, actually I have already specified the path, here I use $file_name just to protect my privacy.

**Comment by Skywalker-Harrison** [comment]
> you need to give the accurate audio and image path，like xxx.mp3 not <$audio_path>

And then I found by deleting the "<" and ">" punctuation, it works, lol

**Comment by vinthony** [comment]
close since it was solved
