### ISSUE TITLE
帮我看看啥原因，全部模型我已经重新下载好几次了，还是提示我缺少similarity_Lm3D_all，无解了

### ISSUE THREAD

**Issue by JINXIAOYU111** [OpenTalker/SadTalker#286]
H:\novelAI\novelai-webui\novelai-webui-aki-v2\models\SadTalker\auido2pose_00140-model.pth
H:\novelAI\novelai-webui\novelai-webui-aki-v2\models\SadTalker\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\scipy\io\matlab\_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\novelAI\\novelai-webui\\novelai-webui-aki-v2\\models\\SadTalker\\BFM_Fitting\\similarity_Lm3D_all.mat'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2/extensions/SadTalker\src\utils\preprocess.py", line 57, in __init__
    self.lm3d_std = load_lm3d(dir_of_BFM_fitting)
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2/extensions/SadTalker\src\face3d\util\load_mats.py", line 107, in load_lm3d
    Lm3D = loadmat(osp.join(bfm_folder, 'similarity_Lm3D_all.mat'))
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\scipy\io\matlab\_mio.py", line 224, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "contextlib.py", line 135, in __enter__
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\scipy\io\matlab\_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "H:\novelAI\novelai-webui\novelai-webui-aki-v2\py310\lib\site-packages\scipy\io\matlab\_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\novelAI\\novelai-webui\\novelai-webui-aki-v2\\models\\SadTalker\\BFM_Fitting\\similarity_Lm3D_all.mat'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

帮我看看啥原因，全部模型我已经重新下载好几次了，还是提示我缺少similarity_Lm3D_all，无解了

**Comment by vinthony** [comment]
checkpoint中，BFM_Fitting这个文件夹好像没下？或者有解压BFM_Fittings.zip吗

**Comment by odinwang** [comment]
遇到了同样的问题，后来发现是浏览器自作聪明把这个文件当作病毒拦截了，根本没下载
