### ISSUE TITLE
Webui gives out Error

### ISSUE THREAD

**Issue by TheWorldIsOur** [OpenTalker/SadTalker#295]
Hello SD Community,

im trying to run Sadtalker on my PC, i basically followed the tutorial(https://www.youtube.com/watch?v=AoIzJWnQw1M) , i didnt have python but i successfully isntalled it.

Now im at like 4:20 in the Video and my Webui gives the following Error out:

venv folder already exists, skipping creation...

venv "venv\Scripts\Python.exe"

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

Commit hash: <none>

Traceback (most recent call last):

File "D:\Sadtalker\SadTalker-main\[Launcher.py](https://launcher.py/)", line 196, in <module>

prepare_environment()

File "D:\Sadtalker\SadTalker-main\[Launcher.py](https://launcher.py/)", line 184, in prepare_environment

run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")

File "D:\Sadtalker\SadTalker-main\[Launcher.py](https://launcher.py/)", line 110, in run_python

return run(f'"{python}" -c "{code}"', desc, errdesc)

File "D:\Sadtalker\SadTalker-main\[Launcher.py](https://launcher.py/)", line 86, in run

raise RuntimeError(message)

RuntimeError: Error running command.

Command: "D:\Sadtalker\SadTalker-main\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"

Error code: 1

stdout: <empty>

stderr: Traceback (most recent call last):

File "<string>", line 1, in <module>

AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

Launch unsuccessful. Exiting.

Drücken Sie eine beliebige Taste . . .

---------------------------------------------------------------------------

So ive seen in another Post on reddit on sadtalker that they deleted venv folder and startet webui again so it reinstalls the folder. it worked for some people but not for me. I get the same Error. Anybody know why? Im just trying to run this Programm...

Any help is highly appreciated!

Thanks in advance everybody

**Comment by vinthony** [comment]
If you do have not GPU on your machine, try to  remove this line:

https://github.com/OpenTalker/SadTalker/blob/d3b2727b4afb4944b9185715d868d01e200e831a/launcher.py#L184
