### ISSUE TITLE
SD1.5下生成失败，请高人指点

### ISSUE THREAD

**Issue by devsosimple** [OpenTalker/SadTalker#307]
shape_predictor_68_face_landmarks.dat  这个模型重新下载过了。
请问该怎么解决啊？

详细出错提示如下：

F:\stable-diffusion-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
F:\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 69, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "F:\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 52, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "F:\stable-diffusion-webui/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 28, in __init__
    self.det_net = init_detection_model('retinaface_resnet50', half=False,device=device, model_rootpath=root_path)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\facexlib\detection\__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "F:\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "F:\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 451297 more bytes. The file might be corrupted.

**Comment by vinthony** [comment]
好像还是这个文件的问题，试试重新下载？

**Comment by devsosimple** [comment]
> 好像还是这个文件的问题，试试重新下载？

shape_predictor_68_face_landmarks.dat  您是说这个文件吗？
这个文件我本来是手动迅雷下载的，后面从github里的google drive又下载覆盖了，还是一样的出错提示。
还有什么可能性？

**Comment by devsosimple** [comment]
> 好像还是这个文件的问题，试试重新下载？

shape_predictor_68_face_landmarks.dat 您是说这个文件吗？
这个文件我本来是手动迅雷下载的，后面从github里的google drive又下载覆盖了，还是一样的出错提示。
还有什么可能性？

**Comment by vinthony** [comment]
试试这个：https://github.com/OpenTalker/SadTalker/releases/download/v0.0.2/shape_predictor_68_face_landmarks.dat
