### ISSUE TITLE
EOFError: Ran out of input 

### ISSUE THREAD

**Issue by frageddy** [OpenTalker/SadTalker#321]
ubuntu@ubuntu:~/SadTalker$ python3 inference.py --driven_audio ~/下载/1.wav                     --source_image /home/ubuntu/图片/1.png                     --enhancer gfpgan 
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
./checkpoints/epoch_20.pth
./checkpoints/auido2pose_00140-model.pth
./checkpoints/auido2exp_00300-model.pth
./checkpoints/facevid2vid_00189-model.pth.tar
./checkpoints/mapping_00229-model.pth.tar
Traceback (most recent call last):
  File "/home/ubuntu/SadTalker/inference.py", line 158, in <module>
    main(args)
  File "/home/ubuntu/SadTalker/inference.py", line 65, in main
    animate_from_coeff = AnimateFromCoeff(free_view_checkpoint, mapping_checkpoint, 
  File "/home/ubuntu/SadTalker/src/facerender/animate.py", line 58, in __init__
    self.load_cpk_facevid2vid(free_view_checkpoint, kp_detector=kp_extractor, generator=generator, he_estimator=he_estimator)
  File "/home/ubuntu/SadTalker/src/facerender/animate.py", line 83, in load_cpk_facevid2vid
    checkpoint = torch.load(checkpoint_path, map_location=torch.device(device))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by huangbaichao** [comment]
I met the same error message. How to solve it?

**Comment by shihzenq** [comment]
您们解决了吗，我也是同样的问题
