### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '4148464d-fa39-4b9a-a79c-45d86ad0b5f7.mp4'

### ISSUE THREAD

**Issue by frageddy** [OpenTalker/SadTalker#324]
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '4148464d-fa39-4b9a-a79c-45d86ad0b5f7.mp4' -> './results/3be9e232-173a-4588-8062-a433332264bc/image##1-0-100.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/SadTalker/src/gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "/home/ubuntu/SadTalker/src/facerender/animate.py", line 188, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "/home/ubuntu/SadTalker/src/utils/videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '4148464d-fa39-4b9a-a79c-45d86ad0b5f7.mp4'

运行aap.py文件时遇到这个问题

**Comment by lupinzema** [comment]
I had the same problem, but I solved it by adding the path of the folder where ffmpeg.exe is installed to the environment variable.
