### ISSUE TITLE
RuntimeError: unexpected EOF, expected 6475634 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by odicchan** [OpenTalker/SadTalker#337]
D:\SD\stable-diffusion-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
D:\SD\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
D:\SD\stable-diffusion-webui\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\Administrator\AppData\Local\Temp\gradio\b9e782ef027bee0e41d7ab312a675d3bf9ee7212\tmpnsjoygot.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.24s/it]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 14.29it/s]
mel:: 100%|██████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 100007.25it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 366.75it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 100/100 [00:36<00:00,  2.71it/s]
ffmpeg version 2023-05-31-git-baa9fccf8d-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 16.100 / 60. 16.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\SD\stable-diffusion-webui\outputs\SadTalker\4f9fd5f3-8ecd-448b-ad11-ad7771c8571f\temp_tmpnsjoygot##chinese_news-0-100.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:08.00, start: 0.000000, bitrate: 112 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x256, 109 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[aist#1:0/pcm_s16le @ 0000022c58fdec40] Guessed Channel Layout: stereo
Input #1, wav, from 'D:\SD\stable-diffusion-webui\outputs\SadTalker\4f9fd5f3-8ecd-448b-ad11-ad7771c8571f\chinese_news-0-100.wav':
  Duration: 00:00:08.00, bitrate: 512 kb/s
  Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, 2 channels, s16, 512 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to '828de34f-7064-42c3-9947-9b0c69093b01.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.5.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x256, q=2-31, 109 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc60.16.100 aac
[out#0/mp4 @ 0000022c58fdee40] video:107kB audio:101kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.052023%
frame=  200 fps=0.0 q=-1.0 Lsize=     214kB time=00:00:07.93 bitrate= 221.3kbits/s speed=27.5x
[aac @ 0000022c59599200] Qavg: 60500.137
The generated video is named tmpnsjoygot##chinese_news-0-100.mp4 in D:\SD\stable-diffusion-webui\outputs\SadTalker\4f9fd5f3-8ecd-448b-ad11-ad7771c8571f
The generated video is named tmpnsjoygot##chinese_news-0-100 in D:\SD\stable-diffusion-webui\outputs\SadTalker\4f9fd5f3-8ecd-448b-ad11-ad7771c8571f
D:\SD\stable-diffusion-webui\extensions\SadTalker\checkpoints\auido2pose_00140-model.pth
D:\SD\stable-diffusion-webui\extensions\SadTalker\checkpoints\shape_predictor_68_face_landmarks.dat
D:\SD\stable-diffusion-webui\extensions\SadTalker\checkpoints\facevid2vid_00189-model.pth.tar
C:\Users\Administrator\AppData\Local\Temp\gradio\b9e782ef027bee0e41d7ab312a675d3bf9ee7212\tmpsc2_61gq.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.52it/s]
3DMM Extraction In Video:: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 100.00it/s]
mel:: 100%|██████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 200014.50it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 769.24it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 100/100 [00:37<00:00,  2.63it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 280) to (256, 288) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
ffmpeg version 2023-05-31-git-baa9fccf8d-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 16.100 / 60. 16.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\SD\stable-diffusion-webui\outputs\SadTalker\c9f19faf-7586-4599-966a-2683a899cda6\temp_tmpsc2_61gq##chinese_news-0-100.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:08.00, start: 0.000000, bitrate: 56 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x288, 53 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
[aist#1:0/pcm_s16le @ 000001f52c89edc0] Guessed Channel Layout: stereo
Input #1, wav, from 'D:\SD\stable-diffusion-webui\outputs\SadTalker\c9f19faf-7586-4599-966a-2683a899cda6\chinese_news-0-100.wav':
  Duration: 00:00:08.00, bitrate: 512 kb/s
  Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, 2 channels, s16, 512 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'de7ee155-f715-4840-8702-1cabd8731401.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.5.100
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 256x288, q=2-31, 53 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc60.16.100 aac
[out#0/mp4 @ 000001f52c852cc0] video:52kB audio:101kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4.080880%
frame=  200 fps=0.0 q=-1.0 Lsize=     160kB time=00:00:07.93 bitrate= 165.1kbits/s speed=27.1x
[aac @ 000001f52c89bd40] Qavg: 60500.137
The generated video is named tmpsc2_61gq##chinese_news-0-100.mp4 in D:\SD\stable-diffusion-webui\outputs\SadTalker\c9f19faf-7586-4599-966a-2683a899cda6
face enhancer....
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\SD\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 122, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess)
  File "D:\SD\stable-diffusion-webui/extensions/SadTalker\src\facerender\animate.py", line 207, in generate
    enhanced_images = face_enhancer(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
  File "D:\SD\stable-diffusion-webui/extensions/SadTalker\src\utils\face_enhancer.py", line 71, in enhancer
    restorer = GFPGANer(
  File "d:\sd\stable-diffusion-webui\venv\scripts\gfpgan\gfpgan\utils.py", line 92, in __init__
    loadnet = torch.load(model_path)
  File "D:\sd\stable-diffusion-webui\modules\safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "D:\sd\stable-diffusion-webui\modules\safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 6475634 more bytes. The file might be corrupted.

**Comment by odicchan** [comment]
The output video is blurry, please help

**Comment by odicchan** [comment]
问题关闭,真的就是纯纯的内存不足,换了个5秒的音频文件,没有任何报错信息了.
