### ISSUE TITLE
生成一开始就报错，大佬帮帮萌新吧！！

### ISSUE THREAD

**Issue by AkaBob0516** [OpenTalker/SadTalker#338]
Traceback (most recent call last):
  File "E:\bob\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\bob\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\bob\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\bob\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\bob\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by lovewanity** [comment]
me2

**Comment by vinthony** [comment]
Similar to https://github.com/OpenTalker/SadTalker/issues/342, it might be a bug of SDWEBUI. you can run the `webui.bat`/`webui.sh` in extensions/sadtalker to run sadtalker alone.
