### ISSUE TITLE
Error when running on google colab

### ISSUE THREAD

**Issue by mayhemantt** [OpenTalker/SadTalker#341]
I tried running the model on the colab notebook directly from the link given in the readme file, here is the error I am getting 
```WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
Traceback (most recent call last):
  File "inference.py", line 144, in <module>
    main(args)
  File "inference.py", line 36, in main
    preprocess_model = CropAndExtract(sadtalker_paths, device)
  File "/content/SadTalker/SadTalker/src/utils/preprocess.py", line 56, in __init__
    checkpoint = torch.load(sadtalker_path['path_of_net_recon_model'], map_location=torch.device(device))    
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/epoch_20.pth'```

when executing this block 
```
# selected audio from exmaple/driven_audio
img = 'examples/source_image/{}.png'.format(default_head_name.value)
print(img)
!python3.8 inference.py --driven_audio ./examples/driven_audio/RD_Radio31_000.wav \
           --source_image {img} \
           --result_dir ./results --still --preprocess full --enhancer gfpgan
```

I downloaded the model from the link given in the readme used the google drive link but i dont how and where to place it 

can someone please provide a updated code or instruction to follow 

Thanks and Regards

**Comment by Kuduxaaa** [comment]
I have some problem

**Comment by vinthony** [comment]
sorry for this, there is a link error when downloading the model. I have updated the code now.
