### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by gnmorfu** [OpenTalker/SadTalker#343]
Running into an issue when trying to install. How could I solve it?

This is what the webui.bat says after installing everything and trying to run the WebUI.

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "H:\AI\SadTalker\Launcher.py", line 199, in <module>
    start()
  File "H:\AI\SadTalker\Launcher.py", line 192, in start
    from app import sadtalker_demo
  File "H:\AI\SadTalker\app.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "H:\AI\SadTalker\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "H:\AI\SadTalker\src\utils\preprocess.py", line 9, in <module>
    from src.face3d.util.preprocess import align_img
  File "H:\AI\SadTalker\src\face3d\util\preprocess.py", line 5, in <module>
    from scipy.io import loadmat
  File "H:\AI\SadTalker\venv\lib\site-packages\scipy\io\__init__.py", line 98, in <module>
    from .matlab import loadmat, savemat, whosmat
  File "H:\AI\SadTalker\venv\lib\site-packages\scipy\io\matlab\__init__.py", line 45, in <module>
    from ._mio import loadmat, savemat, whosmat
  File "H:\AI\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 9, in <module>
    from ._mio4 import MatFile4Reader, MatFile4Writer
  File "H:\AI\SadTalker\venv\lib\site-packages\scipy\io\matlab\_mio4.py", line 8, in <module>
    import scipy.sparse
  File "H:\AI\SadTalker\venv\lib\site-packages\scipy\sparse\__init__.py", line 267, in <module>
    from ._csr import *
  File "H:\AI\SadTalker\venv\lib\site-packages\scipy\sparse\_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

Launch unsuccessful. Exiting.

**Comment by JD1234JD1234** [comment]
yeah i got this too while trying to install it as standalone, tried changing numpy version but couldn't get it working. Tried with automatic1111 but that gave me a new error

**Comment by gnmorfu** [comment]
Yesterday it was running seamlessly in standalone. But I had to delete and reinstall in and.... I can't get it back to work Uff..
I got it working in Auto1111 too, but I really need it standalone so I can call it with no input :(

**Comment by JD1234JD1234** [comment]
I fixed it!
I had to return to the previous commit with `git commit c11aa145cf9cf9d745c1cb90064734def798a545`
although I hadn't originally installed it with git so I had to redownload the whole thing with `git clone https://github.com/Winfredy/SadTalker.git `
works perfect now

**Comment by gnmorfu** [comment]
OMG you're amazing! Thank you!! <3

**Comment by lovewanity** [comment]
这个是因为numba==0.55.1需求numpy==1.21.6，但是其他文件有需要numpy==1.23.4,而产生的，就像上楼说的那样，用以前的版本吧。

**Comment by vinthony** [comment]
fixed in new release.

**Comment by gnmorfu** [comment]
Great!
