### ISSUE TITLE
推理过程报错

### ISSUE THREAD

**Issue by huidabao** [OpenTalker/SadTalker#345]
Traceback (most recent call last):
  File "inference.py", line 159, in <module>
    main(args)
  File "inference.py", line 56, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/home/csj/home/csj/pythonProject/SadTalker/src/utils/preprocess.py", line 51, in __init__
    self.croper = Croper(path_of_lm_croper)
  File "/home/csj/home/csj/pythonProject/SadTalker/src/utils/croper.py", line 38, in __init__
    self.predictor = dlib.shape_predictor(path_of_lm)
RuntimeError: Error deserializing object of type int64
   while deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::vector
在运行推理时，出现这两个包的错误。各位优秀的工程师们，请问怎么去解决？

**Comment by vinthony** [comment]
可以尝试新版本的代码，不需要dlib的环境。

如果是旧版本，确认你有下载好https://github.com/OpenTalker/SadTalker/releases/download/v0.0.2/shape_predictor_68_face_landmarks.dat
