### ISSUE TITLE
没GPU,在CPU上运行出错！源码里需要怎么改？

### ISSUE THREAD

**Issue by luochaolun** [OpenTalker/SadTalker#346]
python inference.py --cpu --driven_audio mydir/1.wav --source_image mydir/face.jpg --enhancer gfpgan
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
Traceback (most recent call last):
  File "E:\wav2lip\SadTalker\inference.py", line 144, in <module>
    main(args)
  File "E:\wav2lip\SadTalker\inference.py", line 36, in main
    preprocess_model = CropAndExtract(sadtalker_paths, device)
  File "E:\wav2lip\SadTalker\src\utils\preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "E:\wav2lip\SadTalker\src\utils\croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "E:\wav2lip\SadTalker\src\face3d\extract_kp_videos_safe.py", line 27, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "D:\Program Files\Python39\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\Program Files\Python39\lib\site-packages\torch\serialization.py", line 1043, in _legacy_load
    result = unpickler.load()
  File "D:\Program Files\Python39\lib\site-packages\torch\serialization.py", line 980, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "D:\Program Files\Python39\lib\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "D:\Program Files\Python39\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "D:\Program Files\Python39\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by vinthony** [comment]
可能需要更新到新版本的 facexlib==0.3.0

**Comment by luochaolun** [comment]
更新 facexlib==0.3.0 后，cpu还是上边的错误

**Comment by ZoomQuiet** [comment]
## fix
根据文档创建的是 3.8 环境, 基于 miniconda:
所以, 对应修改:
~/miniconda3/envs/sadtalker/lib/python3.8/site-packages/facexlib/alignment/__init__.py

![zshot 2023-06-11 16 31 48](https://github.com/OpenTalker/SadTalker/assets/22494/32fdac2e-e528-4163-b788-e6fe25c9199d)

### running

![2291686472495_ pic](https://github.com/OpenTalker/SadTalker/assets/22494/5a0ec5a3-c363-4a2c-ad9a-dd4fbf06f1f0)

![2301686472495_ pic](https://github.com/OpenTalker/SadTalker/assets/22494/b02abc60-3c5d-41ae-93f8-799156830cf1)


可怜的 CPU ...

### OS:

```

$ neofetch
            .-/+oossssoo+/-.               zoomq@i3SPAM
        `:+ssssssssssssssssss+:`           ------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.6 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: UN65U
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-194-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 7 hours, 44 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2677
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.20
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel i3-7100U (4) @ 2.400GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: Intel HD Graphics 620
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 1116MiB / 7848MiB
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
