### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by fidding** [OpenTalker/SadTalker#362]
系统：Apple M1 Pro
版本：macOS Ventura13.2.1
音频与文件：examples里的同名文件

请问生成视频的时候失败了，提示

```shell
 python inference.py --driven_audio ~/Downloads/chinese_news.wav \
--source_image ~/Downloads/art_4.png \
--enhancer gfpgan
./checkpoints/epoch_20.pth
./checkpoints/auido2pose_00140-model.pth
./checkpoints/auido2exp_00300-model.pth
./checkpoints/facevid2vid_00189-model.pth.tar
./checkpoints/mapping_00229-model.pth.tar
3DMM Extraction for source image
landmark Det::   0%|                                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]

landmark Det:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.52s/it]
3DMM Extraction In Video::   0%|                                                                                                                                                                          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 72, in main
    first_coeff_path, crop_pic_path, crop_info =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess, source_image_flag=True)
  File "/Users/hongjiahuang/www/zhuyuan/SadTalker/src/utils/preprocess.py", line 144, in generate
    trans_params, im1, lm1, _ = align_img(frame, lm1, self.lm3d_std)
  File "/Users/hongjiahuang/www/zhuyuan/SadTalker/src/face3d/util/preprocess.py", line 101, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
``` 

![image](https://github.com/OpenTalker/SadTalker/assets/10766926/fd8a7aff-18f6-430b-9e35-790f1988916d)

需要怎么解决？

**Comment by fidding** [comment]
解决了，numpy版本太高导致的，我这边环境版本numpy==1.24.1，将版本降到同requirement.text一致就行。

**Comment by fidding** [comment]
解决了，numpy版本太高导致的，我这边环境版本numpy==1.24.1，将版本降到同requirement.text一致就行。

**Comment by xuxuxbaobao2** [comment]
没用呀   还有其他地方要改么

**Comment by fidding** [comment]
> 没用呀 还有其他地方要改么

我这边之前是降低numpy版本就好了，确认下其他包有没有版本问题。

**Comment by xuxuxbaobao2** [comment]
> > It's useless, is there any other place to change?
> 
> On my side, it's good to lower the numpy version before.,Confirm if there are version problems with other packages.。

Solved

> > 没用呀 还有其他地方要改么
> 
> 我这边之前是降低numpy版本就好了，确认下其他包有没有版本问题。

解决了  感谢回复
