### ISSUE TITLE
TypeError: test() takes from 3 to 7 positional arguments but 10 were given

### ISSUE THREAD

**Issue by sflowing** [OpenTalker/SadTalker#364]
Using in SD webui.
SadTalker extension info:
`SadTalker | https://github.com/OpenTalker/SadTalker.git | a810cbe1 (Tue Jun 6 16:09:05 2023) `
Found error after clicking "Generate":
```
Traceback (most recent call last):
  File "/work/repo/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/work/repo/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/work/repo/stable-diffusion-webui/venv/lib/python3.9/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/work/repo/stable-diffusion-webui/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/work/repo/stable-diffusion-webui/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/work/repo/stable-diffusion-webui/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: test() takes from 3 to 7 positional arguments but 10 were given
```

**Comment by gwind55** [comment]
aflter git update  reset stable diffusion, not reload stable diffusion

**Comment by sflowing** [comment]
The problem has been Solved.
"conda activate sadtalker" with python 3.8 (3.9 not ok), the sadtalker extension works again.
