### ISSUE TITLE
How to solve this？PLZ

### ISSUE THREAD

**Issue by Mr-Poole3** [OpenTalker/SadTalker#375]
Loading weights [fc2511737a] from E:\AI\sd.webui\webui\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
"
            SadTalker will not support download all the files from hugging face, which will take a long time.

            please manually set the SADTALKER_CHECKPOINTS in `webui_user.bat`(windows) or `webui_user.sh`(linux)

**Comment by Mr-Poole3** [comment]
Errors encountered at runtime：
Traceback (most recent call last):
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by xianlilun** [comment]
Same question ,同じ質問,동일한 질문,Même question,Тот же вопрос,同问

**Comment by vinthony** [comment]
have you downloaded the checkpoint from the readme by yourselves?

**Comment by Mr-Poole3** [comment]
Sorry, but I got this error after I downloaded the checkpoint：

WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
{'wav2lip_checkpoint': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/wav2lip.pth', 'audio2pose_checkpoint': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/auido2pose_00140-model.pth', 'audio2exp_checkpoint': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/auido2exp_00300-model.pth', 'free_view_checkpoint': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar', 'path_of_net_recon_model': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/epoch_20.pth', 'dir_of_BFM_fitting': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': False, 'mappingnet_checkpoint': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/mapping_00229-model.pth.tar', 'facerender_yaml': 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/src/config\\facerender.yaml'}
Error verifying pickled file from E:\AI\sd.webui\webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar:
Traceback (most recent call last):
  File "E:\AI\sd.webui\webui\modules\safe.py", line 136, in load_with_extra
    check_pt(filename, extra_handler)
  File "E:\AI\sd.webui\webui\modules\safe.py", line 82, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "zipfile.py", line 1249, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\AI\\sd.webui\\webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar'


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.


Traceback (most recent call last):
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\AI\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\AI\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AI\sd.webui\webui/extensions/SadTalker\src\gradio_demo.py", line 44, in test
    self.animate_from_coeff = AnimateFromCoeff(self.sadtalker_paths, self.device)
  File "E:\AI\sd.webui\webui/extensions/SadTalker\src\facerender\animate.py", line 65, in __init__
    self.load_cpk_facevid2vid(sadtalker_path['free_view_checkpoint'], kp_detector=kp_extractor, generator=generator, he_estimator=he_estimator)
  File "E:\AI\sd.webui\webui/extensions/SadTalker\src\facerender\animate.py", line 119, in load_cpk_facevid2vid
    generator.load_state_dict(checkpoint['generator'])
TypeError: 'NoneType' object is not subscriptable

**Comment by sbersier** [comment]
I don't think "chilloutmix_NiPrunedFp32Fix.safetensors" has anything to do with SadTalker. It is a Lora model for text2img or img2img in Automatic1111.
Could you check again?

**Comment by sbersier** [comment]
I'm on Linux:
I used the stable-diffusion-webui/extensions/SadTalker/scripts/download_models.sh script and it worked.
It downloaded all the required models (except for the SadTalker_V0.0.2_512.safetensors which I manually downloaded from https://github.com/OpenTalker/SadTalker/releases and put into the stable-diffusion-webui/extensions/SadTalker/checkpoints folder

**Comment by sbersier** [comment]
Apparently, there is PR for a cross-platform download_model script:
https://github.com/OpenTalker/SadTalker/pull/327
It looks like the PR was accepted and you can download a python script:
[scripts/download_models.py](https://github.com/OpenTalker/SadTalker/pull/327/commits/f7feb224c27732f7bd0282884a135dc3e28fa4d5#diff-dfa61a4799f0436cc3c9db673a195791a54967813658506d3ff47466c3635b52)

**Comment by vinthony** [comment]
are you putting them in the right place?  for example, you can check this file: E:\AI\sd.webui\webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar

**Comment by x999xmot** [comment]
> are you putting them in the right place? for example, you can check this file: E:\AI\sd.webui\webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar

my extensions folder for sadtalker did not create a "checkpoints" folder for me to place the downloaded checkpoints/models in. Please advise on where to place the downloaded checkpoints.
