### ISSUE TITLE
Traceback error format

### ISSUE THREAD

**Issue by Tobe2d** [OpenTalker/SadTalker#378]
I am have this error whenever I try pressing Generate. However it was working before the update of the face model resolution 512.

```
Traceback (most recent call last):
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "E:\Ai__Project\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
```

**Comment by Tobe2d** [comment]
My installed versions:

version: v1.3.2
 python: 3.10.11
 torch: 2.0.1+cu118
 xformers: 0.0.17
gradio: 3.32.0
checkpoint: e1441589a6

**Comment by zfkun** [comment]
You can directly modify the source code of `facexlib` to solve the problem temporarily. 
For more information, u can see [issue](https://github.com/OpenTalker/SadTalker/issues/346#issuecomment-1578810085). 

Modify location in 

`{your python path}/site-packages/facexlib/alignment/__init__.py` line 19 

```model.load_state_dict(torch.load(model_path, map_location=device)['state_dict'], strict=True)``` 

> I just passed the input parameter `device` directly to save trouble.  - -!
> You can also write 'cpu' directly

**Comment by xpeng** [comment]
This is an issue of ui_tempdir.py and is fixed at: #https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/6095ade1479d5f86f5fc62872af1efde922905dc

**Comment by chanson83** [comment]
Same problem.
Modified facexlib and updated stable-diffusion-webui as above.
Same problem.
Somebody help me!

**Comment by vinthony** [comment]
> 

Have you try the latest SDWEBUI version?

**Comment by chanson83** [comment]
Yes. I tried. It worked well last week. And I updated SDWEBUI and then not worked. Are you guys working with sadtalker well? only not me?

**Comment by vinthony** [comment]
The current code works for me. I have tested a lot.

**Comment by Tobe2d** [comment]
> You can directly modify the source code of `facexlib` to solve the problem temporarily. For more information, u can see [issue](https://github.com/OpenTalker/SadTalker/issues/346#issuecomment-1578810085).
> 
> Modify location in
> 
> `{your python path}/site-packages/facexlib/alignment/__init__.py` line 19
> 
> `model.load_state_dict(torch.load(model_path, map_location=device)['state_dict'], strict=True)`
> 
> > I just passed the input parameter `device` directly to save trouble.  - -!
> > You can also write 'cpu' directly

Did not work for me

**Comment by brianfertig** [comment]
Same here -- no luck with the fix to __init__.py.
I've also completely blown out and reinstalled my venv directory, and I'm on a fresh download of SadTracker as well.

**Comment by yinghanzi** [comment]
之前安装的是好好的，重装了之后就是这个问题，一模一样……

**Comment by AngeWoo** [comment]
When can I update Sadtalker? I use gradio 3.32 /3.33 /3.34/ 3.35 and can't use Sadtalker until now, please

**Comment by vinthony** [comment]
3.31 is ok, and i will try to upgrade gradio for testing
