### ISSUE TITLE
想請教一下..原本更新前都還可以正常使用.6/5更新後就變這樣了

### ISSUE THREAD

**Issue by jarry-LU** [OpenTalker/SadTalker#381]
敬愛的作者您好
非常熱愛您的這一個套件.先表達由衷的感謝
只是6/5更新後
就出現這樣的訊息:
Management and PYTORCH_CUDA_ALLOC_CONF
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
{'wav2lip_checkpoint': 'D:\\AI-SD02\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\wav2lip.pth', 'audio2pose_checkpoint': 'D:\\AI-SD02\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\auido2pose_00140-model.pth', 'audio2exp_checkpoint': 'D:\\AI-SD02\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\auido2exp_00300-model.pth', 'free_view_checkpoint': 'D:\\AI-SD02\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\facevid2vid_00189-model.pth.tar', 'path_of_net_recon_model': 'D:\\AI-SD02\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\epoch_20.pth', 'dir_of_BFM_fitting': 'D:\\AI-SD02\\stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'D:\\AI-SD02\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'D:\\AI-SD02\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': False, 'mappingnet_checkpoint': 'D:\\AI-SD02\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\mapping_00109-model.pth.tar', 'facerender_yaml': 'D:\\AI-SD02\\stable-diffusion-webui/extensions/SadTalker/src/config\\facerender_still.yaml'}
Traceback (most recent call last):
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI-SD02\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 42, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "D:\AI-SD02\stable-diffusion-webui/extensions/SadTalker\src\test_audio2coeff.py", line 38, in __init__
    self.audio2pose_model = self.audio2pose_model.to(device)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 8.00 GiB total capacity; 7.32 GiB already allocated; 0 bytes free; 7.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

不曉得該做哪些處理呢?

**Comment by vinthony** [comment]
感觉是out-of-memory了，可以试试减小batch size？

**Comment by vinthony** [comment]
这里也有一个设置可以帮上忙【https://github.com/OpenTalker/SadTalker/blob/main/docs/FAQ.md】
<img width="1074" alt="image" src="https://github.com/OpenTalker/SadTalker/assets/4397546/8cde64c9-cc9b-45c8-8789-134d53a843cb">

**Comment by jarry-LU** [comment]
好的. 我再試試~

**Comment by jarry-LU** [comment]
不好意思
試了調整batch size為1
一樣出現
Traceback (most recent call last):
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
Traceback (most recent call last):
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
Traceback (most recent call last):
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "D:\AI-SD02\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by vinthony** [comment]
这个是SD的问题哈，可以参考https://github.com/OpenTalker/SadTalker/issues/378#issuecomment-1585527113

**Comment by jarry-LU** [comment]
您好
今天嘗試改為安裝 單機版(不再靠SD)
結果改出現下列這樣的訊息
Traceback (most recent call last):
  File "F:\sadtalk\SadTalker\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sadtalk\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "F:\sadtalk\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\sadtalk\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\sadtalk\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\sadtalk\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\sadtalk\SadTalker\src\gradio_demo.py", line 49, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "F:\sadtalk\SadTalker\src\test_audio2coeff.py", line 50, in __init__
    raise Exception("Failed in loading audio2pose_checkpoint")
Exception: Failed in loading audio2pose_checkpoint

請問是遺漏哪個沒安裝呢?

**Comment by jarry-LU** [comment]
重新改為獨立安裝後
穩定運行了!
感謝!

**Comment by vinthony** [comment]
enjoy!
