### ISSUE TITLE
安装Stable diffusion 插件 运行的时候一直是这个提示…

### ISSUE THREAD

**Issue by yinghanzi** [OpenTalker/SadTalker#383]
Traceback (most recent call last):
  File "/home/adu/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/adu/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/adu/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/adu/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/home/adu/anaconda3/envs/sd/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by vinthony** [comment]
这个可能是gradio的版本问题，你的gradio版本是多少呢？

**Comment by vinthony** [comment]
you may also refer to this issue, it seems to be the bug of SDWEBUI: https://github.com/OpenTalker/SadTalker/issues/378

**Comment by yinghanzi** [comment]
感谢，我之前安装的是好好的重装之后就遇到这种情况了。
