### ISSUE TITLE
Error on Use Reference Video in the new stand-alone version

### ISSUE THREAD

**Issue by ShmuelRonen** [OpenTalker/SadTalker#387]
I put a source image, input audio and a Reference Video and get an error

Here is the CMD list:

using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_512.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00109-model.pth.tar', 'facerender_yaml': 'src/config\\facerender_still.yaml'}
C:\Users\Public\Documents\Wondershare\CreatorTemp\gradio\1f0ff394303a1883f0d075f8519a22f31dee8dd0\image.png
new audiopath: ./results/9a0aff4b-e486-456c-b4a3-bbeda61ae663\look6.mp4.wav
[out#0/wav @ 000001fea37787c0] Output file does not contain any stream
landmark Det:: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.35it/s]
3DMM Extraction In Video:: 100%|███████████████████████████████████████████████████████| 1/1 [00:00<00:00, 62.50it/s]
using ref video for genreation
3DMM Extraction for the reference video providing pose
landmark Det:: 100%|███████████████████████████████████████████████████████████████| 291/291 [00:23<00:00, 12.55it/s]
3DMM Extraction In Video:: 100%|███████████████████████████████████████████████████| 291/291 [00:04<00:00, 64.85it/s]
Face Renderer:: 100%|██████████████████████████████████████████████████████████████| 146/146 [01:22<00:00,  1.76it/s]
Traceback (most recent call last):
  File "C:\sad\SadTalker\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sad\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "C:\sad\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sad\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sad\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\sad\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\sad\SadTalker\src\gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "C:\sad\SadTalker\src\facerender\animate.py", line 215, in generate
    sound = AudioSegment.from_file(audio_path)
  File "C:\sad\SadTalker\venv\lib\site-packages\pydub\audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "C:\sad\SadTalker\venv\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: './results/9a0aff4b-e486-456c-b4a3-bbeda61ae663\\look6.mp4.wav'
![sad](https://github.com/OpenTalker/SadTalker/assets/80190186/d8f592ba-890d-4662-b6eb-2c044a75e298)

**Comment by vinthony** [comment]
it seems your reference video does not contain any audio. Have you tested the pose or blink mode? it is running well?

**Comment by ShmuelRonen** [comment]
Thanks ! my mistake

**Comment by vinthony** [comment]
cool!

**Comment by imomin** [comment]
@ShmuelRonen I am running latest version from main branch. My web UI looks different than yours. I don't see "Reference Video" section.

**Comment by ShmuelRonen** [comment]
> @ShmuelRonen I am running latest version from main branch. My web UI looks different than yours. I don't see "Reference Video" section.

You must install the new stand alone version.
![sad1](https://github.com/OpenTalker/SadTalker/assets/80190186/a71d2f7d-07bd-4b84-b57a-23f605cbec11)

**Comment by ShmuelRonen** [comment]
> No luck! Maybe, it's different for Mac? I followed the same steps (twice).

Try to install it on Linux under Mac
