### ISSUE TITLE
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'`

### ISSUE THREAD

**Issue by croftie** [OpenTalker/SadTalker#393]
Webui extension is installed. The tab is visible.

on start of webui the terminal shows 
`SadTalker will not support download all the files from hugging face, which will take a long time.
             
            please manually set the SADTALKER_CHECKPOINTS in `webui_user.bat`(windows) or `webui_user.sh`(linux)
`

Getting error above on all attempts to execute SadTalker with mp3 sound file and png image

`Textual inversion embeddings loaded(0): 
Model loaded in 11.5s (load weights from disk: 1.6s, create model: 0.9s, apply weights to model: 7.5s, apply half(): 0.8s, move model to device: 0.6s).
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'`

FFMPEG is installed... anything I am missing?

**Comment by vinthony** [comment]
you can refer to #392 , which is a bug of sdwebui
