### ISSUE TITLE
AttributeError: _2D

### ISSUE THREAD

**Issue by AFAP** [OpenTalker/SadTalker#400]
(sadtalker) D:\ai\SadTalker>python inference.py --driven_audio D:\ai\temp\16.wav --source_image D:\ai\temp\msk.png --result_dir D:\ai\temp --still --preprocess full --enhancer gfpgan
./checkpoints\epoch_20.pth
Traceback (most recent call last):
  File "inference.py", line 158, in <module>
    main(args)
  File "inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "D:\ai\SadTalker\src\utils\preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "D:\ai\SadTalker\src\face3d\extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, device=device)
  File "D:\ai\anaconda\envs\sadtalker\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

你好，以上这个报错是哪里有问题吗？还能给点思路提示，目前我查询获得的帮助比较少

**Comment by vinthony** [comment]
face_alignment库的问题。新版本的代码已经不需要这个依赖了。

**Comment by AFAP** [comment]
> face_alignment库的问题。新版本的代码已经不需要这个依赖了。

感谢，我来拉下最新的代码覆盖进去。我是按照bilibili那个使用anaconda的方式做的，前几天还是可操作的，今天换了个服务器同样的步骤安装没有问题，最后执行生成视频的命令报错了

**Comment by vinthony** [comment]
这个可能得查看一下face_alignment版本。可能新的版本没有这个_2D了。

**Comment by fanyhchn** [comment]
修改SadTalker/src/face3d/extract_kp_videos.py 第16行 face_alignment.LandmarksType._2D 为 face_alignment.LandmarksType.TWO_D 就可以了

**Comment by AFAP** [comment]
> 

非常感谢，这个问题我解决了，解决的方式也很简单，就是把最新的源码拉下来，覆盖后执行转换命令时，会自动提示原有的模型不对，然后自动下载下来了最新的。另外就是我设置镜像源就会出问题，镜像速速飞快，下载都是10M+,但是不设置镜像，虽然很慢，只有100K左右，但是最后能成功

**Comment by AFAP** [comment]
> 非常感谢，这个问题我解决了，解决的方式也很简单，就是把最新的源码拉下来，覆盖后执行转换命令时，会自动提示原有的模型不对，然后自动下载下来了最新的。另外就是我设置镜像源就会出问题，镜像速速飞快，下载都是10M+,但是不设置镜像，虽然很慢，只有100K左右，但是最后能成功



> 修改SadTalker/src/face3d/extract_kp_videos.py 第16行 face_alignment.LandmarksType._2D 为 face_alignment.LandmarksType.TWO_D 就可以了

非常感谢，这个问题我解决了，解决的方式也很简单，就是把最新的源码拉下来，覆盖后执行转换命令时，会自动提示原有的模型不对，然后自动下载下来了最新的。另外就是我设置镜像源就会出问题，镜像速速飞快，下载都是10M+,但是不设置镜像，虽然很慢，只有100K左右，但是最后能成功

**Comment by ossky666** [comment]
> 修改SadTalker/src/face3d/extract_kp_videos.py 第16行 face_alignment.LandmarksType._2D 为 face_alignment.LandmarksType.TWO_D 就可以了

**你好，我用你的方法修改了，还是报错，请问有其他处理方法吗？谢谢 。**

/content/stable-diffusion-webui/extensions/SadTalker/checkpoints/shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 64, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "/content/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/content/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, device=device)
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: _TWO_D

**Comment by Yuziyi1117** [comment]
> face_alignment
AttributeError: _TWO_D 前面多了一个_

**Comment by Yuziyi1117** [comment]
> > 修改SadTalker/src/face3d/extract_kp_videos.py 第16行 face_alignment.LandmarksType._2D 为 face_alignment.LandmarksType.TWO_D 就可以了
> 
> **你好，我用你的方法修改了，还是报错，请问有其他处理方法吗？谢谢 。**
> 
> /content/stable-diffusion-webui/extensions/SadTalker/checkpoints/shape_predictor_68_face_landmarks.dat Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict output = await app.get_blocks().process_api( File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api result = await self.call_function( File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function prediction = await anyio.to_thread.run_sync( File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) File "/content/stable-diffusion-webui/modules/call_queue.py", line 13, in f res = func(*args, **kwargs) File "/content/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 64, in test self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device) File "/content/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 46, in **init** self.kp_extractor = KeypointExtractor(device) File "/content/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos.py", line 16, in **init** self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, device=device) File "/usr/lib/python3.10/enum.py", line 437, in **getattr** raise AttributeError(name) from None AttributeError: _TWO_D

_TWO_D前面多了一个下划线
