### ISSUE TITLE
RuntimeError: unexpected EOF, expected 8968 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by JunSong1** [OpenTalker/SadTalker#406]
![image](https://github.com/OpenTalker/SadTalker/assets/40349823/c16fcdd1-e71d-4454-8de2-a89940a97978)

using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1346, in process_api
    result = await self.call_function(
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1074, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\src\gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\src\utils\preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\src\utils\croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\src\face3d\extract_kp_videos_safe.py", line 27, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\sd_webui\sd-webui-aki-v4.1\extensions\SadTalker\venv\lib\site-packages\torch\serialization.py", line 938, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 8968 more bytes. The file might be corrupted.

**Comment by MelvinZang** [comment]
重新安装sadtalker，再生成一次，看一下具体是哪一个模型下载失败，然后手动下载下来放到目标目录。

**Comment by MelvinZang** [comment]
类似：Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/alignment_WFLW_4HG.pth" to E:\PythonWorkspace\stable-diffusion-webui\extensions\SadTalker\gfpgan\weights\alignment_WFLW_4HG.pth

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 172M/185M [00:09<00:00, 19.0MB/s]
Traceback (most recent call last):
