### ISSUE TITLE
 line 422, in run_predict     output = await app.get_blocks().process_api

### ISSUE THREAD

**Issue by Gcode808** [OpenTalker/SadTalker#418]
Startup time: 33.8s (import torch: 9.8s, import gradio: 3.7s, import ldm: 0.9s, other imports: 4.0s, setup codeformer: 0.3s, list SD models: 0.5s, load scripts: 10.0s, create ui: 4.2s, gradio launch: 0.4s).
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by iEdric** [comment]
pip uninstall gradio
pip install gradio==3.31.0

**Comment by Gcode808** [comment]
> pip uninstall gradio pip install gradio==3.31.0

thanks for the quick reply. that still didn't work. Getting the same error. I tried with .mp3 and .wav
