### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import (0.0.2-rc version)

### ISSUE THREAD

**Issue by Mixomo** [OpenTalker/SadTalker#419]
Hello, I have this problem. I have already tried to update, downgrade, re-install NumPy and Scipy and it is still the same. 
Is there any solution? 

I think I'm using the [latest commit](https://github.com/OpenTalker/SadTalker/issues/343#issuecomment-1578812325)

`venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\Launcher.py", line 199, in <module>
    start()
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\Launcher.py", line 192, in start
    from app import sadtalker_demo
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\app.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\src\utils\preprocess.py", line 9, in <module>
    from src.face3d.util.preprocess import align_img
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\src\face3d\util\preprocess.py", line 5, in <module>
    from scipy.io import loadmat
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\__init__.py", line 98, in <module>
    from .matlab import loadmat, savemat, whosmat
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\matlab\__init__.py", line 45, in <module>
    from ._mio import loadmat, savemat, whosmat
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 9, in <module>
    from ._mio4 import MatFile4Reader, MatFile4Writer
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\matlab\_mio4.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\sparse\__init__.py", line 267, in <module>
    from ._csr import *
  File "C:\Users\Win10\Desktop\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\sparse\_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

Launch unsuccessful. Exiting.`

**Comment by TheWorldIsOur** [comment]
same here .... i updated numpy and it still doesnt work. apparantly we are using 0xe while we should use 0xf. In other issue threads i found it seems like the numPy version 0xe needs to be installed and then you can install it because apparently if not it installs the right version in the process, deletes it tho and downloads the wrong version. Idk why but it really gets on my nerves. I just want to get it running...

**Comment by FuzzySilk** [comment]
I'm having same issue

**Comment by Zerthura** [comment]
Same problem. Numpy 1.23.4 version is declared in requirements. So? What to do? If I change it to 1.22 then I will create other issues.
Why requirements seem to be wrong version? 
I don't know what to do to solve this.
Same problem on two different computers.
Please help me to solve

**Comment by Zerthura** [comment]
maybe the problem is because after torch, it install numpy 1.25 before to install requirements?
after it should install requirements numpy 1.23.4 but finally in site-packages it appear numpy 1.21.6.
I have no idea how to proceed. Windows11

venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch==1.12.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp310-cp310-win_amd64.whl (2143.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 GB 1.5 MB/s eta 0:00:00
Collecting torchvision==0.13.1+cu113
  Downloading https://download.pytorch.org/whl/cu113/torchvision-0.13.1%2Bcu113-cp310-cp310-win_amd64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 5.7 MB/s eta 0:00:00
Collecting torchaudio==0.12.1
  Downloading https://download.pytorch.org/whl/cu113/torchaudio-0.12.1%2Bcu113-cp310-cp310-win_amd64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.5 MB/s eta 0:00:00
Collecting typing-extensions
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Downloading Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 2.5 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.25.0-cp310-cp310-win_amd64.whl (15.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.0/15.0 MB 5.0 MB/s eta 0:00:00
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting idna<4,>=2.5
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 kB 1.8 MB/s eta 0:00:00
Installing collected packages: urllib3, typing-extensions, pillow, numpy, idna, charset-normalizer, certifi, torch, requests, torchvision, torchaudio
Successfully installed certifi-2023.5.7 charset-normalizer-3.1.0 idna-3.4 numpy-1.25.0 pillow-9.5.0 requests-2.31.0 torch-1.12.1+cu113 torchaudio-0.12.1+cu113 torchvision-0.13.1+cu113 typing-extensions-4.6.3 urllib3-2.0.3

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\Launcher.py", line 199, in <module>
    start()
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\Launcher.py", line 192, in start
    from app import sadtalker_demo
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\app.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\src\utils\preprocess.py", line 9, in <module>
    from src.face3d.util.preprocess import align_img
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\src\face3d\util\preprocess.py", line 5, in <module>
    from scipy.io import loadmat
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\__init__.py", line 98, in <module>
    from .matlab import loadmat, savemat, whosmat
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\matlab\__init__.py", line 45, in <module>
    from ._mio import loadmat, savemat, whosmat
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\matlab\_mio.py", line 9, in <module>
    from ._mio4 import MatFile4Reader, MatFile4Writer
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\io\matlab\_mio4.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\sparse\__init__.py", line 267, in <module>
    from ._csr import *
  File "C:\Users\shula\SadTalker-0.0.2-rc\SadTalker-0.0.2-rc\venv\lib\site-packages\scipy\sparse\_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

Launch unsuccessful. Exiting.
Premere un tasto per continuare . . .

**Comment by pajeet-dev** [comment]
Has anyone found a work around  ????

**Comment by Mixomo** [comment]
I found a way to make it work. You need to install the AUTOMATIC111 webUI with Stable Diffusion, then install SadTalker as a WebUI extension, and then you can use it in standalone by going to the path (which in my case is) "C:\UsersWin10\Desktop\Local SD\stable-diffusion-webui\extensions\SadTalker".

I hope it helps!

**Comment by Zerthura** [comment]
Thanks, I can confirm this solved, I found same solution to make it works but forget to publish.

**Comment by xiaofanku** [comment]
> Thanks, I can confirm this solved, I found same solution to make it works but forget to publish. But following this way it doesn't save videos, only manually download

哪要下哪个版本的？

**Comment by Zerthura** [comment]
> > Thanks, I can confirm this solved, I found same solution to make it works but forget to publish. But following this way it doesn't save videos, only manually download
> 
> 哪要下哪个版本的？

Install it as a webui extension
