### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0这个错误是否跟图片的五官有关

### ISSUE THREAD

**Issue by seaung** [OpenTalker/SadTalker#420]
Hi,我遇到了一个错误，具体报错如下所示
执行命令为 : python ./inference.py --driven_audio ./audios/2023_06_17_16_10_09.wav --source_image ./examples/source_image/robot.png --result_dir ./videos/2023_06_17_16_10_14 --still --preprocess resize --enhancer gfpgan
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
3DMM Extraction for source image
landmark Det::   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\SadTalker\inference.py", line 144, in <module>
    main(args)
  File "D:\SadTalker\inference.py", line 46, in main
    first_coeff_path, crop_pic_path, crop_info =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess,\
  File "D:\SadTalker\src\utils\preprocess.py", line 124, in generate
    lm = self.propress.predictor.extract_keypoint(frames_pil, landmarks_path)
  File "D:\SadTalker\src\face3d\extract_kp_videos_safe.py", line 39, in extract_keypoint
    current_kp = self.extract_keypoint(image)
  File "D:\SadTalker\src\face3d\extract_kp_videos_safe.py", line 57, in extract_keypoint
    bboxes = bboxes[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

这个错误是否跟图片的五官有关系？我的图片如下所示

![5293_1687014352_hd](https://github.com/OpenTalker/SadTalker/assets/34149191/a605dd30-cf2f-4f61-9d34-a629cb64071d)

**Comment by seaung** [comment]
果然如此，谢谢
