### ISSUE TITLE
无法部署

### ISSUE THREAD

**Issue by yeyi913** [OpenTalker/SadTalker#421]
Using cached https://pypi.tuna.tsinghua.edu.cn/packages/66/05/21a93eed7ff800f7c3b0538eb12bde89660a44693624cd0e49141beccb8b/lmdb-1.4.1-cp310-cp310-win_amd64.whl (100 kB)
Requirement already satisfied: requests in j:\ai2.0汾\sadtalker-main\sadtalker-main\venv\lib\site-packages (from basicsr==1.4.2->-r requirements.txt (line 16)) (2.31.0)
INFO: pip is looking at multiple versions of scikit-image to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of joblib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of yacs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of kornia to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pydub to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of resampy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of librosa to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of imageio-ffmpeg to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of imageio to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of face-alignment to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.

stderr: ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement tb-nightly (from basicsr) (from versions: none)
ERROR: No matching distribution found for tb-nightly

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Launch unsuccessful. Exiting.

**Comment by vber** [comment]
I have the same problem. my env is mac m1 macos-13.4.1.

**Comment by Carzit** [comment]
I noticed that you are using cached “pypi.tuna.tsinghua.edu.cn”. This caused problems during the deployment process of this project. The reason for the failure was that some files that needed to be downloaded could not be downloaded.
I suggest to use the official channel.

**Comment by zergtant** [comment]
> I noticed that you are using cached “pypi.tuna.tsinghua.edu.cn”. This caused problems during the deployment process of this project. The reason for the failure was that some files that needed to be downloaded could not be downloaded. I suggest to use the official channel.

yes ,i search this issues by google, and same problem. and im sure this is tsinghua mirror problem.
change it to tencent(douban) https://pypi.douban.com/simple/,and install successful

**Comment by yeyi913** [comment]
> > 我注意到您正在使用缓存的“pypi.tuna.tsinghua.edu.cn”。这在该项目的部署过程中导致了问题。失败的原因是无法下载某些需要下载的文件。我建议使用官方渠道。
> 
> 是的，我通过谷歌搜索这个问题，同样的问题。我确定这是清华镜子问题。改为腾讯（豆瓣）https://pypi.douban.com/simple/,and 安装成功

我改用腾讯（豆瓣）还是报错venv "venv\Scripts\Python.exe"
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "Launcher.py", line 204, in <module>
    start()
  File "Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "G:\AI数字人\SadTalker-main\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
请按任意键继续. . .

**Comment by Carzit** [comment]
it's not a problem about `pip` i think. Actually the information shows that maybe there's something wrong with your `gradio` module. If your code has no mistake, try to change your gradio version or just uninstall and install it.
