### ISSUE TITLE
Got this error: safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

### ISSUE THREAD

**Issue by fxgeoffrey** [OpenTalker/SadTalker#424]
python inference.py --driven_audio chinese_news.wav --source_image msk.png --enhancer gfpgan --result_dir abc.mp4
using safetensor as default
Traceback (most recent call last):
  File "/home/hadoop-mtai/jeff/SadTalker/inference.py", line 144, in <module>
    main(args)
  File "/home/hadoop-mtai/jeff/SadTalker/inference.py", line 36, in main
    preprocess_model = CropAndExtract(sadtalker_paths, device)
  File "/home/hadoop-mtai/jeff/SadTalker/src/utils/preprocess.py", line 53, in __init__
    checkpoint = safetensors.torch.load_file(sadtalker_path['checkpoint'])
  File "/home/hadoop-mtai/.conda/envs/sadtalker/lib/python3.9/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

**Comment by fxgeoffrey** [comment]
Issue resolved after completely download the models
