### ISSUE TITLE
needs one of codec_name or template

### ISSUE THREAD

**Issue by liyuanfan** [OpenTalker/SadTalker#426]
3DMM Extraction for source image
landmark Det:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.43it/s]
3DMM Extraction In Video:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.32it/s]
mel:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 136/136 [00:00<00:00, 49166.12it/s]
audio2exp:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 317.64it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68/68 [00:08<00:00,  8.27it/s]
Traceback (most recent call last):
  File "inference.py", line 144, in <module>
    main(args)
  File "inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/root/autodl-tmp/SadTalker/src/facerender/animate.py", line 205, in generate
    imageio.mimsave(path, result,  fps=float(25))
  File "/root/miniconda3/envs/sadtalker/lib/python3.8/site-packages/imageio/v2.py", line 484, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/root/miniconda3/envs/sadtalker/lib/python3.8/site-packages/imageio/plugins/pyav.py", line 634, in write
    self.init_video_stream(codec, fps=fps, pixel_format=out_pixel_format)
  File "/root/miniconda3/envs/sadtalker/lib/python3.8/site-packages/imageio/plugins/pyav.py", line 846, in init_video_stream
    stream = self._container.add_stream(codec, fps)
  File "av/container/output.pyx", line 60, in av.container.output.OutputContainer.add_stream
ValueError: needs one of codec_name or template
How to solve it? Thank you vary much!

**Comment by Json0926** [comment]
Solve it?

**Comment by ppy2017** [comment]
同样问题，请问解决了吗

**Comment by zsszyx** [comment]
same question

**Comment by HMT-SolutionDevelopment** [comment]
I had the same issue and I fixed it after installing the missing package imageio-ffmpeg. 
Hence, you can check if the package "imageio-ffmpeg" has been installed yet.
On my side, this issue did not relate to imageio or pyav package
