### ISSUE TITLE
解决 TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by yuan199696** [OpenTalker/SadTalker#430]
更改gradio版本为3.31.0
 pip install --upgrade gradio==3.31.0
执行第一遍可能版本没改过来，最好执行两边以上命令！

**Comment by shameforest** [comment]
I have the same error

**Comment by AIMusicExperiment** [comment]
glad to hear that I'm not the only one with this problem. Hopefully they can fix it.

**Comment by gioppino** [comment]
Bump, same problem here
Window 10
python 3.11.4 (i know, i must downgrade, this will be my first attempt tomorrow)

Stack trace:
`Traceback (most recent call last):
  File "D:\<mypath>\venv\Lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\<mypath>\venv\Lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\<mypath>\venv\Lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\<mypath>\venv\Lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\<mypath>\venv\Lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'`

**Comment by AIMusicExperiment** [comment]
Changing the requirements_versions.txt in the stable-diffusion-webui directory to gradio==3.31.0 fixed the problem!!!! YAY!

**Comment by gioppino** [comment]
> gradio==3.31.0
on 
>  requirements_versions.txt
I confirm this solve the problem

**Comment by lijiguang2014** [comment]
I have changed requirements_versions.txt, but same problem here
the follow txt is the content of my requirements_versions.txt
pytest-base-url~=2.0
pytest-cov~=4.0
pytest~=7.3
gradio==3.31.0

My OS is Mac os 12.1

Traceback (most recent call last):
  File "/Users/mac/Documents/stableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/mac/Documents/stableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/mac/Documents/stableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/mac/Documents/stableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/Users/mac/Documents/stableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

**Comment by gtbloody** [comment]
牛的，解决

**Comment by vinthony** [comment]
Hi, I have tested on SDWEBUI v1.4.0, the whole pipeline is ok even `gradio == 3.32.0`, please give more information(SDWEBUI version and platform) if you face the same problem of `[TypeError: save_pil_to_file() got an unexpected keyword argument 'format'](https://github.com/OpenTalker/SadTalker/issues/430#top)`
