### ISSUE TITLE
There is a problem running in stubby diffusion。

### ISSUE THREAD

**Issue by BennyDixon** [OpenTalker/SadTalker#435]
I downloaded checkpoints and gfpgan and placed them under extensions\SadTalker.

Traceback (most recent call last):
  File "C:\Ai_SW\SD-WebUI-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Ai_SW\SD-WebUI-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Ai_SW\SD-WebUI-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Ai_SW\SD-WebUI-aki-v4.1\python\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "C:\Ai_SW\SD-WebUI-aki-v4.1\python\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
![1](https://github.com/OpenTalker/SadTalker/assets/137192344/cd8f968c-eeb4-45cc-9a5f-0e5e5daeff43)
![2](https://github.com/OpenTalker/SadTalker/assets/137192344/6496a15e-f092-439f-a73e-2225a347f1ae)

**Comment by BennyDixon** [comment]
I am using v0.0.2rc version

**Comment by LitenBuzzTh** [comment]
I am also facing this issue. Any news?

**Comment by vinthony** [comment]
gradio版本的问题，SD需要gradio==3.21.0
