### ISSUE TITLE
sadtakler 新版本错误

### ISSUE THREAD

**Issue by wxfcgzht** [OpenTalker/SadTalker#438]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1792, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 52, in decode_base64_to_image
    exif = img.getexif()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1040, in getexif
    return super().getexif()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1454, in getexif
    self._exif.load(exif_info)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3670, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\TiffImagePlugin.py", line 504, in __init__
    raise SyntaxError(msg)
SyntaxError: not a TIFF file (header b"b'Exif\\x" not valid)

**Comment by vinthony** [comment]
可能输入的图像应该有问题？

**Comment by SauChi666** [comment]
Traceback (most recent call last):
  File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'. 

Same here, M2 Pro

**Comment by vinthony** [comment]
> Traceback (most recent call last): File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict output = await app.get_blocks().process_api( File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api inputs = self.preprocess_data(fn_index, inputs, state) File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data processed_input.append(block.preprocess(inputs[i])) File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess return self._format_image(im) File "/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image path = self.pil_to_temp_file( TypeError: save_pil_to_file() got an unexpected keyword argument 'format'.
> 
> Same here, M2 Pro

It can be solved via : https://github.com/OpenTalker/SadTalker/issues/444#issuecomment-1608864829

I have also tested SDWEBUI V1.4.0 on my computer with SadTalker, it works fine on my computer.

**Comment by sgergdfgerhtehet** [comment]
> > 回溯（最近一次调用）：文件“/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py”，第 422 行，在run_predict输出 = await app.get_blocks（）.process_api（ 文件 “/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py”，第 1321 行，在 process_api 输入 = self.preprocess_data（fn_index，输入，状态）文件 “/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py”， 第 1171 行，在 preprocess_data processed_input.append（block.preprocess（inputs[i]）） 文件中 “/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py”，第 1848 行，在预处理中返回 self._format_image（im） 文件 “/Users/appleid/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py”，第 1796 行，在 _format_image path = self.pil_to_temp_file（ TypeError： save_pil_to_file（） 得到一个意外的关键字参数 'format'。
> > 同样在这里，M2 Pro
> 
> 可以通过以下方式解决：[#444（评论）](https://github.com/OpenTalker/SadTalker/issues/444#issuecomment-1608864829)
> 
> 我还在我的电脑上用SadTalker测试了SDWEBUI V1.4.0，它在我的电脑上工作正常。
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
  File "D:\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\gradio\\tmpybl38csm.png'
这个怎么解决？可以帮下吗？
