### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '30b0b348-ca75-4e49-ba18-79a0bf2100d6.mp4'

### ISSUE THREAD

**Issue by Yolanda2020** [OpenTalker/SadTalker#439]
Traceback (most recent call last):
  File "/data/SadTalker-main/inference.py", line 144, in <module>
    main(args)
  File "/data/SadTalker-main/inference.py", line 88, in main
    enhancer=args.enhancer, background_enhancer=args.background_enhancer, preprocess=args.preprocess, img_size=args.size)
  File "/data/SadTalker-main/src/facerender/animate.py", line 222, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "/data/SadTalker-main/src/utils/videoio.py", line 28, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "/opt/conda/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/opt/conda/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '30b0b348-ca75-4e49-ba18-79a0bf2100d6.mp4'
Pleasse tell me how to solve this problem?

**Comment by G-force78** [comment]
How were you using it? Through gradio?

**Comment by MINGSONG4** [comment]
me too! although i can find the mp4 in result folder, but the mp4 are no voice. I try to reinstall but still cannot fix the problem.

**Comment by vinthony** [comment]
have you installed the ffmpeg correctly?

**Comment by vinthony** [comment]
you may check this issue: https://github.com/OpenTalker/SadTalker/issues/356
