### ISSUE TITLE
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully + Error

### ISSUE THREAD

**Issue by Xxredz** [OpenTalker/SadTalker#442]
Hi, when I click Generate, I immediately get a message saying "WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!"

Though I did download the Checkpoints and placed them in checkpoints folder, unless I downloaded older versions?

It still loads and does the process as if it's generating the video but ends with this error:

"Traceback (most recent call last):
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\Stable Diffusion\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 138, in test
    data = get_facerender_data(coeff_path, crop_pic_path, first_coeff_path, audio_path, batch_size, still_mode=still_mode, preprocess=preprocess, size=size, expression_scale = exp_scale)
  File "D:\Stable Diffusion\stable-diffusion-webui/extensions/SadTalker\src\generate_facerender_batch.py", line 65, in get_facerender_data
    remainder = frame_num%batch_size
ZeroDivisionError: integer division or modulo by zero"

How can I fix?

**Comment by georgezouq** [comment]
Same question, What does each value of pose style mean?

**Comment by genialgenteel** [comment]
I'm surprised no one has responded here yet. These are options specific to the Auto1111 GUI implementation of SadTalker, not the backend python scripting. The best practices document doesn't explain what they do.

@vinthony Do you mind adding this info to the FAQ or the best practices document, if not here in this thread? 
Thanks in advance!
