### ISSUE TITLE
3D Face visualization doesnt work

### ISSUE THREAD

**Issue by G-force78** [OpenTalker/SadTalker#449]
Missing many dependencies it seems, I simply copied the code into a collab notebook from here
https://github.com/OpenTalker/SadTalker/blob/main/docs/face3d.md

Traceback (most recent call last):
  File "/content/SadTalker/inference.py", line 8, in <module>
    from src.utils.preprocess import CropAndExtract
  File "/content/SadTalker/src/utils/preprocess.py", line 11, in <module>
    from src.face3d.models import networks
  File "/content/SadTalker/src/face3d/models/__init__.py", line 22, in <module>
    from src.face3d.models.base_model import BaseModel
  File "/content/SadTalker/src/face3d/models/base_model.py", line 9, in <module>
    from . import networks
  File "/content/SadTalker/src/face3d/models/networks.py", line 19, in <module>
    from kornia.geometry import warp_affine
ModuleNotFoundError: No module named 'kornia'

**Comment by vinthony** [comment]
try `pip install korina`

**Comment by G-force78** [comment]
> try `pip install korina`

Kornia was in the res3d file already, I guess it needs another version? Same for yacs

**Comment by vinthony** [comment]
have you download all the checkpoints?

**Comment by G-force78** [comment]
> have you download all the checkpoints?

No I thought it would have already done it, I will try again thanks

**Comment by G-force78** [comment]
I now get this error

Traceback (most recent call last):
  File "/content/SadTalker/inference.py", line 144, in <module>
    main(args)
  File "/content/SadTalker/inference.py", line 79, in main
    from src.face3d.visualize import gen_composed_video
  File "/content/SadTalker/src/face3d/visualize.py", line 5, in <module>
    from src.face3d.models.facerecon_model import FaceReconModel
  File "/content/SadTalker/src/face3d/models/facerecon_model.py", line 11, in <module>
    from src.face3d.util.nvdiffrast import MeshRenderer
  File "/content/SadTalker/src/face3d/util/nvdiffrast.py", line 4, in <module>
    import pytorch3d.ops
ModuleNotFoundError: No module named 'pytorch3d'

Have looked back and found this

ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d
