### ISSUE TITLE
麻烦帮看一下代码，已经按照教程下载所有内容，还是报错，无法正常安装SadTalker

### ISSUE THREAD

**Issue by bboss717** [OpenTalker/SadTalker#453]
系统报错内容如下：
`Installing requirements for SadTalker
Looking in indexes: https://mirror.baidu.com/pypi/simple, https://mirrors.aliyun.com/pypi/simple
Looking in links: https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
Creating model from config: D:\sd-webui-aki-v4.1\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Collecting librosa==0.8.0
  Using cached https://mirrors.aliyun.com/pypi/packages/26/4d/c22d8ca74ca2c13cd4ac430fa353954886104321877b65fa871939e78591/librosa-0.8.0.tar.gz (183 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "D:\sd-webui-aki-v4.1\python\lib\site-packages\setuptools\__init__.py", line 8, in <module>
          import _distutils_hack.override  # noqa: F401
        File "D:\sd-webui-aki-v4.1\python\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
          __import__('_distutils_hack').do_override()
        File "D:\sd-webui-aki-v4.1\python\lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
          ensure_local_distutils()
        File "D:\sd-webui-aki-v4.1\python\lib\site-packages\_distutils_hack\__init__.py", line 64, in ensure_local_distutils
          assert '_distutils' in core.__file__, core.__file__
      AssertionError: D:\sd-webui-aki-v4.1\python\lib\distutils\core.py
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error executing callback ui_tabs_callback for D:\sd-webui-aki-v4.1\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.1\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "D:\sd-webui-aki-v4.1\extensions\SadTalker\scripts\extension.py", line 163, in on_ui_tabs
    install()
  File "D:\sd-webui-aki-v4.1\extensions\SadTalker\scripts\extension.py", line 134, in install
    launch.run_pip("install "+ v, "requirements for SadTalker")
  File "D:\sd-webui-aki-v4.1\modules\launch_utils.py", line 124, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "D:\sd-webui-aki-v4.1\modules\launch_utils.py", line 101, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements for SadTalker.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Command: "D:\sd-webui-aki-v4.1\python\python.exe" -m pip install librosa==0.8.0 --prefer-binary --index-url https://mirror.baidu.com/pypi/simple
Error code: 1`

**Comment by vinthony** [comment]
好像是你的网络问题 没办法正常安装python包
