### ISSUE TITLE
TypeError: FAN.__init__() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by red-sponge** [OpenTalker/SadTalker#463]
preload_extensions_git_metadata for 42 extensions took 4.33s
using safetensor as default
{'checkpoint': 'C:\\Users\\USER\\Documents\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'C:\\Users\\USER\\Documents\\stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'C:\\Users\\USER\\Documents\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'C:\\Users\\USER\\Documents\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'C:\\Users\\USER\\Documents\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'C:\\Users\\USER\\Documents\\stable-diffusion-webui/extensions/SadTalker/src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "C:\Users\USER\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\USER\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\USER\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\USER\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\USER\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\USER\Documents\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\USER\Documents\stable-diffusion-webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\Users\USER\Documents\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "C:\Users\USER\Documents\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "C:\Users\USER\Documents\stable-diffusion-webui/extensions/SadTalker\src\utils\croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "C:\Users\USER\Documents\stable-diffusion-webui/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 45, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)
  File "C:\Users\USER\Documents\stable-diffusion-webui/extensions/SadTalker\src\face3d\extract_kp_videos_safe.py", line 21, in init_alignment_model
    model = FAN(num_modules=4, num_landmarks=98, device=device)
TypeError: FAN.__init__() got an unexpected keyword argument 'device'

**Comment by qfwt308** [comment]
同样问题，怎么解决？

**Comment by rikabi89** [comment]
I am getting error too

**Comment by ZeDoCode** [comment]
![Captura de tela 2023-07-02 180251](https://github.com/OpenTalker/SadTalker/assets/86901186/bcb0fe2e-bf69-46c1-8bf2-db4569c9ebc3)

Same here

**Comment by vinthony** [comment]
which version of the facexlib are you using?

**Comment by vinthony** [comment]
facexlib introduces this new argument in v0.3.0. Here, I fixed it by adding a self FAN function in the new version:
https://github.com/OpenTalker/SadTalker/commit/ae0b26359d44c9379450a8e02a38b45eeec15549

**Comment by ZeDoCode** [comment]
> facexlib introduces this new argument in v0.3.0. Here, I fixed it by adding a self FAN function in the new version: [ae0b263](https://github.com/OpenTalker/SadTalker/commit/ae0b26359d44c9379450a8e02a38b45eeec15549). You can try to update the code.

Hello friend
In my case, I already had this argument in my version of extract_kp_videos_safe.py, so I decided to replace all my_awing_arch.py with the one in the link you posted and it worked perfectly.

Thanks for the idea!
