### ISSUE TITLE
SyntaxError: cannot use starred expression here

### ISSUE THREAD

**Issue by wangyunpeng0319** [OpenTalker/SadTalker#467]
执行：python inference.py --driven_audio 11.mp3 --source_image 1234.jpg --enhancer gfpgan
报错：
Traceback (most recent call last):
  File "/Users/wangyunpeng/sadTalker/SadTalker/inference.py", line 8, in <module>
    from src.utils.preprocess import CropAndExtract
  File "/Users/wangyunpeng/sadTalker/SadTalker/src/utils/preprocess.py", line 11, in <module>
    from src.face3d.models import networks
  File "/Users/wangyunpeng/sadTalker/SadTalker/src/face3d/models/__init__.py", line 22, in <module>
    from src.face3d.models.base_model import BaseModel
  File "/Users/wangyunpeng/sadTalker/SadTalker/src/face3d/models/base_model.py", line 9, in <module>
    from . import networks
  File "/Users/wangyunpeng/sadTalker/SadTalker/src/face3d/models/networks.py", line 19, in <module>
    from kornia.geometry import warp_affine
  File "/Users/wangyunpeng/anaconda3/lib/python3.10/site-packages/kornia/__init__.py", line 12, in <module>
    from kornia import augmentation
  File "/Users/wangyunpeng/anaconda3/lib/python3.10/site-packages/kornia/augmentation/__init__.py", line 1, in <module>
    from .augmentation import *
  File "/Users/wangyunpeng/anaconda3/lib/python3.10/site-packages/kornia/augmentation/augmentation.py", line 7, in <module>
    from . import functional as F
  File "/Users/wangyunpeng/anaconda3/lib/python3.10/site-packages/kornia/augmentation/functional.py", line 488
    input = input.view((-1, (*input.shape[-3:])))
                             ^^^^^^^^^^^^^^^^^
SyntaxError: cannot use starred expression here

**Comment by wangyunpeng0319** [comment]
执行这个命令python inference.py --driven_audio ../output/11.mp3 --source_image ../output/1234.jpg --result_dir ../output --still --preprocess full --enhancer gfpgan也是报同样的错

**Comment by vinthony** [comment]
可能是kornia的版本问题，你的是多少呢

**Comment by wangyunpeng0319** [comment]
> 可能是kornia的版本问题，你的是多少呢

kornia版本0.2.0
<img width="288" alt="image" src="https://github.com/OpenTalker/SadTalker/assets/30229647/3d9d27b1-a356-44d7-bec3-9d274a6435a3">
