### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by L134139** [OpenTalker/SadTalker#469]
Expecting value: line 1 column 1 (char 0)

**Comment by vinthony** [comment]
可以看这个，和墙有关：https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9150

**Comment by L134139** [comment]
Traceback (most recent call last):
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 785, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\002\SadTalker-main-v002dev\src\gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "D:\002\SadTalker-main-v002dev\src\facerender\animate.py", line 183, in generate
    predictions_video = make_animation(source_image, source_semantics, target_semantics,
  File "D:\002\SadTalker-main-v002dev\src\facerender\modules\make_animation.py", line 128, in make_animation
    out = generator(source_image, kp_source=kp_source, kp_driving=kp_norm)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\002\SadTalker-main-v002dev\src\facerender\modules\generator.py", line 251, in forward
    out = self.decoder(out)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\002\SadTalker-main-v002dev\src\facerender\modules\generator.py", line 152, in forward
    x = self.up_1(x, seg)         # 64, 256, 256
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\002\SadTalker-main-v002dev\src\facerender\modules\util.py", line 469, in forward
    dx = self.conv_0(self.actvn(self.norm_0(x, seg1)))
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\002\SadTalker-main-v002dev\src\facerender\modules\util.py", line 439, in forward
    out = normalized * (1 + gamma) + beta
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 2.00 GiB total capacity; 1.59 GiB already allocated; 0 bytes free; 1.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 785, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\002\SadTalker-main-v002dev\src\gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "D:\002\SadTalker-main-v002dev\src\utils\preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "D:\002\SadTalker-main-v002dev\src\utils\croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "D:\002\SadTalker-main-v002dev\src\face3d\extract_kp_videos_safe.py", line 27, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\facexlib\alignment\__init__.py", line 19, in init_alignment_model
    model.load_state_dict(torch.load(model_path)['state_dict'], strict=True)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\serialization.py", line 958, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\serialization.py", line 185, in _cuda_deserialize    return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 2.00 GiB total capacity; 1.67 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 785, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\002\SadTalker-main-v002dev\src\gradio_demo.py", line 49, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "D:\002\SadTalker-main-v002dev\src\test_audio2coeff.py", line 38, in __init__
    self.audio2pose_model = self.audio2pose_model.to(device)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 2.00 GiB total capacity; 1.67 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
Traceback (most recent call last):
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 785, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\002\SadTalker-main-v002dev\src\gradio_demo.py", line 49, in test
    self.audio_to_coeff = Audio2Coeff(self.sadtalker_paths, self.device)
  File "D:\002\SadTalker-main-v002dev\src\test_audio2coeff.py", line 38, in __init__
    self.audio2pose_model = self.audio2pose_model.to(device)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\002\SadTalker-main-v002dev\python38\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 2.00 GiB total capacity; 1.67 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
