### ISSUE TITLE
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

### ISSUE THREAD

**Issue by speewer** [OpenTalker/SadTalker#479]
hello,this error occurs recently,please check it,thanks.

using safetensor as default
{'checkpoint': 'E:\\BaiduNetdiskDownload\\sd-webui-aki-v4.1\\sd-webui-aki-v4.1\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'E:\\BaiduNetdiskDownload\\sd-webui-aki-v4.1\\sd-webui-aki-v4.1/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'E:\\BaiduNetdiskDownload\\sd-webui-aki-v4.1\\sd-webui-aki-v4.1/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'E:\\BaiduNetdiskDownload\\sd-webui-aki-v4.1\\sd-webui-aki-v4.1/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'E:\\BaiduNetdiskDownload\\sd-webui-aki-v4.1\\sd-webui-aki-v4.1\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'E:\\BaiduNetdiskDownload\\sd-webui-aki-v4.1\\sd-webui-aki-v4.1/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\speewer\AppData\Local\Temp\gradio\tmpsv_yvp9f.png
Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1/extensions/SadTalker\src\gradio_demo.py", line 96, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess, True, size)
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1/extensions/SadTalker\src\utils\preprocess.py", line 96, in generate
    x_full_frames, crop, quad = self.propress.crop(x_full_frames, still=True if 'ext' in crop_or_resize.lower() else False, xsize=512)
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1/extensions/SadTalker\src\utils\croper.py", line 128, in crop
    lm = self.get_landmark(img_np)
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1/extensions/SadTalker\src\utils\croper.py", line 35, in get_landmark
    lm = landmark_98_to_68(self.predictor.detector.get_landmarks(img)) # [0]
  File "E:\BaiduNetdiskDownload\sd-webui-aki-v4.1\sd-webui-aki-v4.1/extensions/SadTalker\src\face3d\util\my_awing_arch.py", line 363, in get_landmarks
    img = cv2.resize(img, (256, 256))
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by speewer** [comment]
Problem solved.
Wrong picture was picked,changed another one and it worked, maybe hand on the head affects facial recognition.
