### ISSUE TITLE
[BUG] AssertionError

### ISSUE THREAD

**Issue by Rogal80** [OpenTalker/SadTalker#482]
Hello, I always have the same problem when I generate something. Can you help me?

using safetensor as default
{'checkpoint': 'I:\\Github\\Web_UI\\automatic\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'I:\\Github\\Web_UI\\automatic/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'I:\\Github\\Web_UI\\automatic/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'I:\\Github\\Web_UI\\automatic/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'I:\\Github\\Web_UI\\automatic\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'I:\\Github\\Web_UI\\automatic/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\jerzy\AppData\Local\Temp\gradio\tmpah5bxdx7.png
False None
Traceback (most recent call last):
  File "I:\Github\Web_UI\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Github\Web_UI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "I:\Github\Web_UI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\Github\Web_UI\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\Github\Web_UI\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\Github\Web_UI\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\Github\Web_UI\automatic\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "I:\Github\Web_UI\automatic/extensions/SadTalker\src\gradio_demo.py", line 81, in test
    assert use_ref_video == True and ref_info == 'all'
AssertionError

**Comment by jfcartier** [comment]
Same here. On windows 11

**Comment by onlineapps-cloud** [comment]
same error
