### ISSUE TITLE
Error generate: cv2.error: OpenCV(4.7.0

### ISSUE THREAD

**Issue by Damarcreative** [OpenTalker/SadTalker#484]
Face Renderer:: 100% 59/59 [02:11<00:00,  2.22s/it]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (512, 435) to (512, 448) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
The generated video is named ./results/53d9d035-af88-4bf3-8e5a-7869e1856a8a/image##Selamat Pagi apakah ada yang bisa saya bantu_ hahahaha-0-100.mp4
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
seamlessClone::   0% 0/117 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "/content/SadTalker/src/gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "/content/SadTalker/src/facerender/animate.py", line 230, in generate
    paste_pic(path, pic_path, crop_info, new_audio_path, full_video_path, extended_crop= True if 'ext' in preprocess.lower() else False)
  File "/content/SadTalker/src/utils/paste_pic.py", line 63, in paste_pic
    gen_img = cv2.seamlessClone(p, full_img, mask, location, cv2.NORMAL_CLONE)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/core/src/matrix.cpp:808: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

**Comment by hitzhangjie** [comment]
there's a warning message in your output:
>IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (512, 435) to (512, 448) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).

I came across this issue, too. My input image was 256x384, which could be divisible by the macro_block_size=16, but still failed by the same error.

**Comment by hitzhangjie** [comment]
@vinthony Hi, vinthony, could you please explain how to work around this issue? Thanks.

**Comment by hitzhangjie** [comment]
There's a similar issue https://github.com/OpenTalker/SadTalker/issues/57, which was closed.

My image is 256x384, and the image format is jpg.

**Comment by zhaopu0710** [comment]
How to solve this problem?
