### ISSUE TITLE
can not detect the landmark from source image

### ISSUE THREAD

**Issue by venshine** [OpenTalker/SadTalker#491]
手机前置摄像头自拍的照片，基本是大头照，提示如下信息：
```
using safetensor as default
3DMM Extraction for source image
Traceback (most recent call last):
  File "inference.py", line 144, in <module>
    main(args)
  File "inference.py", line 46, in main
    first_coeff_path, crop_pic_path, crop_info =  preprocess_model.generate(pic_path, first_frame_dir, args.preprocess,\
  File "/mnt/disk-1/venshine/SadTalker/src/utils/preprocess.py", line 103, in generate
    x_full_frames, crop, quad = self.propress.crop(x_full_frames, still=True if 'ext' in crop_or_resize.lower() else False, xsize=512)
  File "/mnt/disk-1/venshine/SadTalker/src/utils/croper.py", line 131, in crop
    raise 'can not detect the landmark from source image'
TypeError: exceptions must derive from BaseException
```
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/venshine/miniconda3/envs/sadtalker/lib/python3.8/site-packages/starlette/responses.py", line 342, in __call__
    raise RuntimeError(f"File at path {self.path} is not a file.")
```
换成Stable-Diffusion生成的人像可以检测出来

**Comment by wasa4587** [comment]
yes me too

WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!
{'wav2lip_checkpoint': 'C:\\Users\\wasa4\\stable-diffusion-webui\\models\\SadTalker\\wav2lip.pth', 'audio2pose_checkpoint': 'C:\\Users\\wasa4\\stable-diffusion-webui\\models\\SadTalker\\auido2pose_00140-model.pth', 'audio2exp_checkpoint': 'C:\\Users\\wasa4\\stable-diffusion-webui\\models\\SadTalker\\auido2exp_00300-model.pth', 'free_view_checkpoint': 'C:\\Users\\wasa4\\stable-diffusion-webui\\models\\SadTalker\\facevid2vid_00189-model.pth.tar', 'path_of_net_recon_model': 'C:\\Users\\wasa4\\stable-diffusion-webui\\models\\SadTalker\\epoch_20.pth', 'dir_of_BFM_fitting': 'C:\\Users\\wasa4\\stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'C:\\Users\\wasa4\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'C:\\Users\\wasa4\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': False, 'mappingnet_checkpoint': 'C:\\Users\\wasa4\\stable-diffusion-webui\\models\\SadTalker\\mapping_00229-model.pth.tar', 'facerender_yaml': 'C:\\Users\\wasa4\\stable-diffusion-webui/extensions/SadTalker/src/config\\facerender.yaml'}
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/alignment_WFLW_4HG.pth" to C:\Users\wasa4\stable-diffusion-webui\extensions\SadTalker\gfpgan\weights\alignment_WFLW_4HG.pth

100%|███████████████████████████████████████████████████████████████████████████████| 185M/185M [00:11<00:00, 17.5MB/s]
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to C:\Users\wasa4\stable-diffusion-webui\models\GFPGAN\detection_Resnet50_Final.pth

100%|███████████████████████████████████████████████████████████████████████████████| 104M/104M [00:04<00:00, 24.5MB/s]
C:\Users\wasa4\AppData\Local\Temp\gradio\tmpbtblrsd1.png
Traceback (most recent call last):
  File "C:\Users\wasa4\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\wasa4\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\wasa4\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\wasa4\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\wasa4\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\wasa4\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\wasa4\stable-diffusion-webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\Users\wasa4\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 96, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess, True, size)
  File "C:\Users\wasa4\stable-diffusion-webui/extensions/SadTalker\src\utils\preprocess.py", line 96, in generate
    x_full_frames, crop, quad = self.propress.crop(x_full_frames, still=True if 'ext' in crop_or_resize.lower() else False, xsize=512)
  File "C:\Users\wasa4\stable-diffusion-webui/extensions/SadTalker\src\utils\croper.py", line 131, in crop
    raise 'can not detect the landmark from source image'

**Comment by radu-gheorghiu** [comment]
@venshine or @wasa4587 , have you found any solutions to this problem?

**Comment by zero-or-one** [comment]
It happens because the model cannot detect the face in the image. Make sure that image contains recognizable human face

**Comment by radu-gheorghiu** [comment]
> @radu-gheorghiu It happens because the model cannot detect the face in the image. Make sure that image contains recognizable human face

After retrying this a few times, I can confirm you are right. The image you use needs to have a recognizable face in it. The face that I used was a carricature image and it was very small relative to the entire image size, hence I got the error.

**Comment by venshine** [comment]
> 

But, It can't recognize the selfie emitted by using the front camera of my phone...

**Comment by venshine** [comment]
> @radu-gheorghiu It happens because the model cannot detect the face in the image. Make sure that image contains recognizable human face


But, It can't recognize the selfie emitted by using the front camera of my phone...
