### ISSUE TITLE
Stable Diffusion web-ui 失败

### ISSUE THREAD

**Issue by hy5424** [OpenTalker/SadTalker#494]
Loading weights [a83e25fe5b] from F:\workspace\aigc\stable-diffusion-webui\models\Stable-diffusion\国风.safetensors
"
            SadTalker will not support download all the files from hugging face, which will take a long time.

            please manually set the SADTALKER_CHECKPOINTS in `webui_user.bat`(windows) or `webui_user.sh`(linux)

*** Error executing callback ui_tabs_callback for F:\workspace\aigc\stable-diffusion-webui\extensions\SadTalker-main\scripts\extension.py
    Traceback (most recent call last):
      File "F:\workspace\aigc\stable-diffusion-webui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "F:\workspace\aigc\stable-diffusion-webui\extensions\SadTalker-main\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
    ModuleNotFoundError: No module named 'app_sadtalker'

**Comment by Goocai** [comment]
i just modify "SadTalker-main" folders name -> "SadTalker"  it's work well

**Comment by shushengshu** [comment]
这个问题解决了吗，我也遇到了同样的问题

**Comment by axengine** [comment]
modify scripts/extension.py:165

`sys.path.append(paths.script_path+'/extensions/SadTalker') `
