### ISSUE TITLE
M1 Mac run error：FileNotFoundError

### ISSUE THREAD

**Issue by zdw19840929** [OpenTalker/SadTalker#499]
M1电脑运行的时候报了这个错误，麻烦大神帮忙看下是咋回事，谢谢啦
Traceback (most recent call last):
  File "/Users/zhangdawei/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/zhangdawei/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/zhangdawei/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/zhangdawei/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/Users/zhangdawei/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
  File "/Users/zhangdawei/stable-diffusion-webui/modules/ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory:
![截屏2023-07-12 23 19 22](https://github.com/OpenTalker/SadTalker/assets/4941590/a6825cdf-b1ac-4de2-9632-604bc42839e6)
 '/var/folders/tq/kz3jychs09v4735lfdtxbsgc0000gn/T/gradio/tmp2kjx96zb.png'

**Comment by itltf512116** [comment]
@zdw19840929 您好，请问怎么解决的这个问题呢？
