### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by zujiapu** [OpenTalker/SadTalker#501]
venv "venv\Scripts\Python.exe"
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
Commit hash: ae0b26359d44c9379450a8e02a38b45eeec15549
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/alignment_WFLW_4HG.pth" to D:\sadtalker\SadTalker\gfpgan\weights\alignment_WFLW_4HG.pth

Traceback (most recent call last):
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "D:\sadtalker\SadTalker\src\gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "D:\sadtalker\SadTalker\src\utils\preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "D:\sadtalker\SadTalker\src\utils\croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "D:\sadtalker\SadTalker\src\face3d\extract_kp_videos_safe.py", line 45, in __init__
    self.detector = init_alignment_model('awing_fan',device=device, model_rootpath=root_path)
  File "D:\sadtalker\SadTalker\src\face3d\extract_kp_videos_safe.py", line 26, in init_alignment_model
    model_path = load_file_from_url(
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\facexlib\utils\misc.py", line 77, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "D:\sadtalker\SadTalker\venv\lib\site-packages\torch\hub.py", line 593, in download_url_to_file
    u = urlopen(req)
  File "C:\ProgramData\anaconda3\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\anaconda3\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\ProgramData\anaconda3\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\ProgramData\anaconda3\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\ProgramData\anaconda3\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\ProgramData\anaconda3\lib\urllib\request.py", line 1352, in do_open
    r = h.getresponse()
  File "C:\ProgramData\anaconda3\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\ProgramData\anaconda3\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\anaconda3\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by WudiJoey** [comment]
maybe you can manually download https://github.com/xinntao/facexlib/releases/download/v0.1.0/alignment_WFLW_4HG.pth and put it on your path（D:\sadtalker\SadTalker\gfpgan\weights\alignment_WFLW_4HG.pth）
