### ISSUE TITLE
Error in launching extension - Traceback attached

### ISSUE THREAD

**Issue by fatualux** [OpenTalker/SadTalker#514]
Hello, first of all thanks for your work.
I have followed the installing instructions, downloaded the models in the right path (the second option), but I encountered this problem.
I am on Arch Linux, last updated kernel.

```
`Restarting UI...
Error executing callback ui_tabs_callback for /home/fz/.virtualenv/stablediffusion/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/home/fz/.virtualenv/stablediffusion/modules/script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/scripts/extension.py", line 172, in on_ui_tabs
    from app_sadtalker import sadtalker_demo
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/app_sadtalker.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/gradio_demo.py", line 6, in <module>
    from src.generate_batch import get_data
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/generate_batch.py", line 8, in <module>
    import src.utils.audio as audio
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/utils/audio.py", line 1, in <module>
    import librosa
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/librosa/core/__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/librosa/core/constantq.py", line 1058, in <module>
    dtype=np.complex,
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.1s (load scripts: 0.4s, create ui: 0.5s).
Closing server running on port: 7860
Restarting UI...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.3s (load scripts: 0.2s, create ui: 0.8s).
Closing server running on port: 7860
Restarting UI...
load Sadtalker Checkpoints from /home/fz/.virtualenv/stablediffusion/extensions/SadTalker/checkpoints
Error executing callback ui_tabs_callback for /home/fz/.virtualenv/stablediffusion/extensions/SadTalker/scripts/extension.py
Traceback (most recent call last):
  File "/home/fz/.virtualenv/stablediffusion/modules/script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/scripts/extension.py", line 172, in on_ui_tabs
    from app_sadtalker import sadtalker_demo
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/app_sadtalker.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/gradio_demo.py", line 6, in <module>
    from src.generate_batch import get_data
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/generate_batch.py", line 8, in <module>
    import src.utils.audio as audio
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/utils/audio.py", line 1, in <module>
    import librosa
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/librosa/core/__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/librosa/core/constantq.py", line 1058, in <module>
    dtype=np.complex,
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`
```

I am not a Python dev, maybe you can give me a tip about how to fix this problem.

I do not even have a SadTalker tab in the WebUi.

Thanks in advance

![image](https://github.com/OpenTalker/SadTalker/assets/35587292/b2e38f4a-6d92-46b0-b1e1-70994e6f1240)

![image](https://github.com/OpenTalker/SadTalker/assets/35587292/09492d20-fac6-4387-8700-3f87ae99b354)

**Comment by fatualux** [comment]
EDIT: I have managed to launch SadTalker, but every time I try to generate a video I get this error:

`Traceback (most recent call last):
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/gradio/blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/fz/.virtualenv/stablediffusion/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/gradio_demo.py", line 138, in test
    data = get_facerender_data(coeff_path, crop_pic_path, first_coeff_path, audio_path, batch_size, still_mode=still_mode, preprocess=preprocess, size=size, expression_scale = exp_scale)
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/generate_facerender_batch.py", line 65, in get_facerender_data
    remainder = frame_num%batch_size
ZeroDivisionError: integer division or modulo by zero
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
using safetensor as default
{'checkpoint': '/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/checkpoints/SadTalker_V0.0.2_512.safetensors', 'dir_of_BFM_fitting': '/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/config', 'audio2pose_yaml_path': '/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/config/auido2pose.yaml', 'audio2exp_yaml_path': '/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/config/auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': '/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/checkpoints/mapping_00229-model.pth.tar', 'facerender_yaml': '/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/config/facerender.yaml'}
/tmp/528a7a7f540ef23d6e7cef46e239347ef2460d0e/tmpco72wfcp.png
landmark Det:: 100%|██████████████████████████████| 1/1 [00:00<00:00, 12.43it/s]
3DMM Extraction In Video:: 100%|██████████████████| 1/1 [00:00<00:00, 59.18it/s]
mel:: 100%|██████████████████████████████████| 32/32 [00:00<00:00, 29305.18it/s]
audio2exp:: 100%|█████████████████████████████████| 4/4 [00:00<00:00, 25.35it/s]
Traceback (most recent call last):
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/gradio/blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/fz/.virtualenv/stablediffusion/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/fz/.virtualenv/stablediffusion/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/gradio_demo.py", line 138, in test
    data = get_facerender_data(coeff_path, crop_pic_path, first_coeff_path, audio_path, batch_size, still_mode=still_mode, preprocess=preprocess, size=size, expression_scale = exp_scale)
  File "/home/fz/.virtualenv/stablediffusion/extensions/SadTalker/src/generate_facerender_batch.py", line 65, in get_facerender_data
    remainder = frame_num%batch_size
ZeroDivisionError: integer division or modulo by zero`

![image](https://github.com/OpenTalker/SadTalker/assets/35587292/c355ff46-3102-413d-8648-0f35a20f6671)

**Comment by fatualux** [comment]
Managed to solve everything

**Comment by ldavis9000aws** [comment]
So what was the fix??

**Comment by fatualux** [comment]
I updated Stable Diffusion WebUI, uninstalled and then reinstalled  the extension.
Unfortunately, after a few days SD WebUI stopped working at all; buttons and flags did not work, with no traceback to debug the issue. I have been trying to fix it for about an hour, then I installed ComfyUI and I am still using it.
