### ISSUE TITLE
MPS support for Apple Silicon

### ISSUE THREAD

**Issue by splicerlabs** [OpenTalker/SadTalker#526]
Thank you for this amazing project. I am currently testing on M1 Pro and I was able to add the following to inference.py in order to use the GPU. However, Conv3d is not currently supported on MPS. Everything works up until the face render.

**Added this to line 141 in inference.py**
```
elif torch.backends.mps.is_available():
    args.device = "mps"
```
**Output:**
```
3DMM Extraction for source image
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.35it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.21it/s]
3DMM Extraction for the reference video providing eye blinking
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:19<00:00, 10.48it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:03<00:00, 57.25it/s]
mel:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 227/227 [00:00<00:00, 131288.89it/s]
227
audio2exp:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 63.88it/s]
Traceback (most recent call last):
  File "inference.py", line 146, in <module>
    main(args)
  File "inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/Users/splicer/Documents/DEVELOPMENT/SadTalker/src/facerender/animate.py", line 183, in generate
    predictions_video = make_animation(source_image, source_semantics, target_semantics,
  File "/Users/splicer/Documents/DEVELOPMENT/SadTalker/src/facerender/modules/make_animation.py", line 109, in make_animation
    kp_canonical = kp_detector(source_image)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/splicer/Documents/DEVELOPMENT/SadTalker/src/facerender/modules/keypoint_detector.py", line 60, in forward
    feature_map = self.predictor(x)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/splicer/Documents/DEVELOPMENT/SadTalker/src/facerender/modules/util.py", line 365, in forward
    out = self.up_blocks(out)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/splicer/Documents/DEVELOPMENT/SadTalker/src/facerender/modules/util.py", line 189, in forward
    out = self.conv(out)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/splicer/miniconda3/envs/sadtalker/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 608, in _conv_forward
    return F.conv3d(
RuntimeError: Conv3D is not supported on MPS
```

**Testing MPS on M1 Pro**
I can get Conv3d to work on CPU device and then return output to MPS device in this simple demo, I am hoping you can do something similar where Conv3d is passed to CPU device and the result is passed back to MPS device. This way we can use the Metal framework for GPU processing via torch. 

```
import torch
x = torch.randn(1, 10, 10, 10, device="mps")
c = torch.nn.Conv3d(1, 1, 3, device="cpu")
c(x.to("cpu"))
```

**Comment by charleybin** [comment]
I have made changes ,it still dosen't work for me.

``` modifications
174 class UpBlock3d(nn.Module):
175     """
176     Upsampling block for use in decoder.
177     """
178 
179     def __init__(self, in_features, out_features, kernel_size=3, padding=1, groups=1):
180         super(UpBlock3d, self).__init__()
181 
182         self.conv = nn.Conv3d(in_channels=in_features, out_channels=out_features, kernel_size=kernel_size,
183                               padding=padding, groups=groups, device="cpu")
184         self.norm = BatchNorm3d(out_features, affine=True)
185 
186     def forward(self, x):
187         # out = F.interpolate(x, scale_factor=(1, 2, 2), mode='trilinear')
188         out = F.interpolate(x, scale_factor=(1, 2, 2))
189         out = self.conv(out)
190         out = self.norm(out)
191         out = F.relu(out)
192         return out
```


```Exceptions:
Traceback (most recent call last):
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/inference.py", line 146, in <module>
    main(args)
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/src/facerender/animate.py", line 183, in generate
    predictions_video = make_animation(source_image, source_semantics, target_semantics,
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/src/facerender/modules/make_animation.py", line 109, in make_animation
    kp_canonical = kp_detector(source_image)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/src/facerender/modules/keypoint_detector.py", line 60, in forward
    feature_map = self.predictor(x)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/src/facerender/modules/util.py", line 365, in forward
    out = self.up_blocks(out)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/bill/code/opensource/ai_code/image_ai/SadTalker/src/facerender/modules/util.py", line 189, in forward
    out = self.conv(out)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/bill/opt/anaconda3/envs/tts/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 608, in _conv_forward
    return F.conv3d(
RuntimeError: Conv3D is not supported on MPS
```

**Comment by turcottep** [comment]
I was able to get it to work with quite a bit of trouble.

First of all, build torch and torchvision from source using the most recent commit in master/main
https://github.com/pytorch/pytorch/tree/main#from-source
https://github.com/pytorch/vision/tree/main

Then apply the changes from this pull request to your built code from torch and rebuild:
https://github.com/pytorch/pytorch/pull/99246/files

Now the Conv3D operation will work, but we need to update code from SadTalker to make it compatible

SadTalker/inference.py  line 139
`    if torch.cuda.is_available() and not args.cpu:
        print("using gpu")
        args.device = "cuda"
    elif torch.backends.mps.is_available() and not args.cpu:
        print("using mps")
        args.device = "mps"
    else:
        print("using cpu")
        args.device = "cpu"
        `

**Comment by turcottep** [comment]
I was able to get it to work with quite a bit of work.

first of all, clone torch and torchvision from main and build them from source.

https://github.com/pytorch/pytorch/tree/main#from-source
https://github.com/pytorch/vision/tree/main

Then apply the changes from this pull request to torch and rebuild it.
https://github.com/pytorch/pytorch/pull/99246/files

Now the Conv3D operation works, but there are changes to make in SadTalker to make it compatible.

SadTalker/inference.py line 139
```diff
    if torch.cuda.is_available() and not args.cpu:
+        print("using gpu")
          args.device = "cuda"
+    elif torch.backends.mps.is_available() and not args.cpu:
+        print("using mps")
+        args.device = "mps"
    else:
+        print("using cpu")
          args.device = "cpu"
```

SadTalker/src/face3d/util/preprocess.py line 101
```diff
-      trans_params = np.array([w0, h0, s, t[0], t[1]])
+     trans_params = np.array([w0, h0, s, t[0, 0], t[1, 0]])

```

These next changes I would call workarounds, I don't know if that's the best way to handle it, but it worked for me:

SadTalker/src/facerender/modules/dense_motion.py line 75
```diff
+   if heatmap.type() == "torch.mps.FloatTensor":
+          zeros = torch.zeros(heatmap.shape[0], 1, spatial_size[0], spatial_size[1], spatial_size[2]).type(heatmap.type(), , device="mps", dtype=torch.float)
+   else:
           zeros = torch.zeros(heatmap.shape[0], 1, spatial_size[0], spatial_size[1], spatial_size[2]).type(heatmap.type())
```

SadTalker/src/facerender/modules/util.py line 40
```diff
+    if type == "torch.mps.FloatTensor":
+        x = torch.arange(w, device="mps", dtype=torch.float)
+        y = torch.arange(h, device="mps", dtype=torch.float)
+    else:
        x = torch.arange(w).type(type)
        y = torch.arange(h).type(type)

...
line 56
+    if type == "torch.mps.FloatTensor":
+        x = torch.arange(w, device="mps", dtype=torch.float)
+        y = torch.arange(h, device="mps", dtype=torch.float)
+        z = torch.arange(d, device="mps", dtype=torch.float)
+    else:
        x = torch.arange(w).type(type)
        y = torch.arange(h).type(type)
        z = torch.arange(d).type(type)
```

Finally, I also modified the gfpgan library to also use mps. I edited the file directly in miniconda3/envs/customtorchenv/lib/python3.8/site-packages/gfpgan/utils.py

gfpgan/utils.py line 37
```diff
-         self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') if device is None else device
+        if device is None:
+            if torch.cuda.is_available():
+                self.device = torch.device("cuda")
+            elif torch.backends.mps.is_available():
+                self.device = torch.device("mps")
+            else:
+                self.device = torch.device("cpu")
+        else:
+            self.device = device
```

Hope this can help someone!

**Comment by sukualam** [comment]
is the speed of processing using this fix is noticeable than using cpu ?

**Comment by karelbecerra** [comment]
> I was able to get it to work with quite a bit of work.
> 
> first of all, clone torch and torchvision from main and build them from source.
> 
> https://github.com/pytorch/pytorch/tree/main#from-source https://github.com/pytorch/vision/tree/main
> 
> Then apply the changes from this pull request to torch and rebuild it. https://github.com/pytorch/pytorch/pull/99246/files
> 
> Now the Conv3D operation works, but there are changes to make in SadTalker to make it compatible.
> 
> Hope this can help someone!
@turcottep I tried with your solution but could compile the code (Mac M1)

Getting errors like this one
`/Convolution.mm:23:6: error: no previous prototype for function 'fill_conv3d_desc' [-Werror,-Wmissing-prototypes]
void fill_conv3d_desc(MPSGraphConvolution3DOpDescriptor* descriptor_,
`

**Comment by genglinxiao** [comment]
From pytorch side, I can see the issue is still open:
https://github.com/pytorch/pytorch/issues/77818

I understand that @turcottep basically rebuild pytorch from source with a pull request to support MPS for Conv3D. If that works, I think we should push from the pytorch side to merge the pull request, and then ask SadTalker to change their code accordingly.
