### ISSUE TITLE
Launch unsuccessful. Exiting. Press any key to continue . . .

### ISSUE THREAD

**Issue by uniquekaiser** [OpenTalker/SadTalker#530]
Hi,

I'm trying to run the script on my windows machine, when i execute webui.bat i get the following error:

C:\projects\sadtalker> .\webui.bat
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Unable to create process using '"C:\Users\hsdgf\AppData\Local\Programs\Python\Python311\python.exe" Launcher.py'

Launch unsuccessful. Exiting.
Press any key to continue . . .

I have Python 11.4 installed and it has the VARIABLE PATH added to the env variables.

Any ideas on how can i fix this error?

Thanks!

**Comment by uniquekaiser** [comment]
I uninstalled Python 3.11.6 and deleted the venv folder, restarted the pc, installed python 3.10.6 and added the variable to path.

It started running the webui.bat script but found an error and stoped there, this was the full execution:

`C:\projects\sadtalker> ./webui.bat
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ae0b26359d44c9379450a8e02a38b45eeec15549
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\Projects\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\Projects\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Projects\SadTalker\app_sadtalker.py", line 29, in sadtalker_demo
    with gr.Blocks(analytics_enabled=False) as sadtalker_interface:
  File "C:\Projects\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1478, in __exit__
    self.app = routes.App.create_app(self)
  File "C:\Projects\SadTalker\venv\lib\site-packages\gradio\routes.py", line 220, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\routing.py", line 706, in decorator
    self.add_api_route(
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\routing.py", line 645, in add_api_route
    route = route_class(
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\routing.py", line 491, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\dependencies\utils.py", line 268, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\dependencies\utils.py", line 111, in get_param_sub_dependant
    return get_sub_dependant(
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\dependencies\utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\dependencies\utils.py", line 289, in get_dependant
    add_param_to_fields(field=param_field, dependant=dependant)
  File "C:\Projects\SadTalker\venv\lib\site-packages\fastapi\dependencies\utils.py", line 462, in add_param_to_fields
    if field_info.in_ == params.ParamTypes.path:
AttributeError: 'FieldInfo' object has no attribute 'in_'

Launch unsuccessful. Exiting.
Press any key to continue . . .`

Any ideas?

**Comment by daarkwulf** [comment]
Did u get idea ?

**Comment by uniquekaiser** [comment]
> Did u get idea ?

I followed this tutorial and I managed to run it: https://youtu.be/yEkLEm-10Mw

I did realize that the python version i was using is not the correct one, it needs a specific older version

**Comment by daarkwulf** [comment]
yeah its 3.10.6 i got it

**Comment by saqibmaqbool786** [comment]
Hi, i installed 3.10.6 version of python. But still i am facing this same issue. kindly help me out.


venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.

**Comment by decimecano** [comment]
> Hi, i installed 3.10.6 version of python. But still i am facing this same issue. kindly help me out.
> 
> venv folder already exists, skipping creation... venv "venv\Scripts\Python.exe" Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Commit hash: [cd4c046](https://github.com/OpenTalker/SadTalker/commit/cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8) Installing requirements for SadTalker WebUI (may take longer time in first time) Launching SadTalker Web UI Traceback (most recent call last): File "C:\SadTalker\Launcher.py", line 204, in start() File "C:\SadTalker\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'
> 
> Launch unsuccessful. Exiting.

did you fixed it?

**Comment by XayerMorgan** [comment]
Same issue here for me:  Traceback (most recent call last):
  File "C:\Dev\SadTalker2\Launcher.py", line 204, in <module>
    start()
  File "C:\Dev\SadTalker2\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\Dev\SadTalker2\app.py", line 37, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by decimecano** [comment]
> Same issue here for me: Traceback (most recent call last): File "C:\Dev\SadTalker2\Launcher.py", line 204, in start() File "C:\Dev\SadTalker2\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\Dev\SadTalker2\app.py", line 37, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'

try this, it didn't worked for me but it may for you, I saw it in  previous post:

pip install gradio==3.41.2

**Comment by XayerMorgan** [comment]
> > Same issue here for me: Traceback (most recent call last): File "C:\Dev\SadTalker2\Launcher.py", line 204, in start() File "C:\Dev\SadTalker2\Launcher.py", line 198, in start demo = sadtalker_demo() File "C:\Dev\SadTalker2\app.py", line 37, in sadtalker_demo with gr.Row().style(equal_height=False): AttributeError: 'Row' object has no attribute 'style'
> 
> try this, it didn't worked for me but it may for you, I saw it in previous post:
> 
> pip install gradio==3.41.2

Thanks for the attempt.  I tried it, and it downgraded from latest to that version, but it still won't run. Funny thing -- two days ago it worked.  Automatic111, FOOOOOCUS work great.  But I ran CCLEANER to free up trash files (like a dope),and that's the only thing that changed.  I deleted everything.  Uninstalled FFMPEG, PYTHON, etc.  I am using PYTHON.ORG for my interpreter and not conda.

**Comment by XayerMorgan** [comment]
If I add the extensions to AUTOMATIC1111 (where it was previously running fine), I get this 
 
 Creating model from config: C:\Users\jrrho\stable-diffusion-webui\configs\v1-inference.yaml
load Sadtalker Checkpoints from C:\Users\jrrho\stable-diffusion-webui\extensions\SadTalker\checkpoints
*** Error executing callback ui_tabs_callback for C:\Users\jrrho\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
    Traceback (most recent call last):
      File "C:\Users\jrrho\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\jrrho\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
      File "C:\Users\jrrho\stable-diffusion-webui/extensions/SadTalker\app_sadtalker.py", line 3, in <module>
        from src.gradio_demo import SadTalker
      File "C:\Users\jrrho\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 6, in <module>
        from src.generate_batch import get_data
      File "C:\Users\jrrho\stable-diffusion-webui/extensions/SadTalker\src\generate_batch.py", line 8, in <module>
        import src.utils.audio as audio
      File "C:\Users\jrrho\stable-diffusion-webui/extensions/SadTalker\src\utils\audio.py", line 1, in <module>
        import librosa
      File "C:\Users\jrrho\stable-diffusion-webui\venv\lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "C:\Users\jrrho\stable-diffusion-webui\venv\lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
      File "C:\Users\jrrho\stable-diffusion-webui\venv\lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
      File "C:\Users\jrrho\stable-diffusion-webui\venv\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details an

**Comment by decimecano** [comment]
this look like a finicky extension indeed.  I might try the Discord version. I give up trying to run the local version.

**Comment by XayerMorgan** [comment]
> this look like a finicky extension indeed. I might try the Discord version. I give up trying to run the local version.

I really want to make this work again.  I was able to cancel DID because of it.  Wish I could determine what changed.  Funny that automatic1111 and foocus work without issues.

**Comment by larryvw1** [comment]
I hope you can help

Traceback (most recent call last):
  File "C:\SadTakler\SadTalker\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\SadTakler\SadTalker\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\SadTakler\SadTalker\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by daarkwulf** [comment]
i think it would be better if u just install the 3.10.6 version freshly and add paths to system settings watch utube for it. and then create venv from vscode software and then install all requirements one by one in python but in vscode select the interpreter as python .. not the microsoft version ok. and then go for instaling sadtalker. it will work perhaps.  rest m providing the link of google drive which i made its pip package .put it in temp folder.as given instruction in drive. and then use the software. as installing sadtalker will take all the requred files from the pip .  https://drive.google.com/drive/folders/1MDhLlJ3mkykBttzC6F2XfSdn-O2b0FPy?usp=drive_link

**Comment by Ruby141002** [comment]
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: cd4c0465ae0b54a6f85af57f5c65fec9fe23e7f8
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "D:\Downloaded app data\Sadtalker\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "D:\Downloaded app data\Sadtalker\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "D:\Downloaded app data\Sadtalker\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .

I am getting the same issue and also tried the method mentioned above: pip install gradio==3.41.2 and i did exactly as the tutorial mentioned in this video https://youtu.be/yEkLEm-10Mw?si=Ch63oAM_VvvsroTc but at the last step it is giving me errors plz help me

**Comment by robertgnv** [comment]
3.10.9 Python... got all the way to.

Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Traceback (most recent call last):
  File "C:\SadTalker\Launcher.py", line 204, in <module>
    start()
  File "C:\SadTalker\Launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "C:\SadTalker\app_sadtalker.py", line 35, in sadtalker_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

Launch unsuccessful. Exiting.
Press any key to continue . . .

**Comment by MaarVFX** [comment]
gradio==3.41.2 worked for me.

I added the version info to requirements.txt and ran it again (there's only "gradio" in there with no specific version, so it installs the latest one)

**Comment by itanitcom** [comment]
worked fine  with  : 
python 3.8.20
pip install gradio==3.41.2

![Image](https://github.com/user-attachments/assets/d94a770b-fcd2-4d09-942a-012811f2ab87)
