### ISSUE TITLE
ValueError:  [!] Model file not found in the output path

### ISSUE THREAD

**Issue by SuperGoodGame** [OpenTalker/SadTalker#536]
安装webui时，TTS报错，缺少模型，我该如何重新安装这个python包，或者如何解决问题

**Comment by SuperGoodGame** [comment]
Python 3.8.17 (default, Jul  5 2023, 21:04:15) 
[GCC 11.2.0]
Commit hash: ae0b26359d44c9379450a8e02a38b45eeec15549
Installing requirements for SadTalker WebUI (may take longer time in first time)
Installing install TTS individually in SadTalker, which might not work on windows.
Launching SadTalker Web UI
No API token found for 🐸Coqui Studio voices - https://coqui.ai 
Visit 🔗https://app.coqui.ai/account to get one.
Set it as an environment variable `export COQUI_STUDIO_TOKEN=<token>`

 > tts_models/multilingual/multi-dataset/your_tts is already downloaded.
Traceback (most recent call last):
  File "launcher.py", line 204, in <module>
    start()
  File "launcher.py", line 198, in start
    demo = sadtalker_demo()
  File "/home/jiahuaw/test/SadTalker/SadTalker/app_sadtalker.py", line 49, in sadtalker_demo
    tts_talker = TTSTalker()
  File "/home/jiahuaw/test/SadTalker/SadTalker/src/utils/text2speech.py", line 9, in __init__
    self.tts = TTS(model_name)
  File "/home/jiahuaw/test/SadTalker/SadTalker/venv/lib/python3.8/site-packages/TTS/api.py", line 289, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/home/jiahuaw/test/SadTalker/SadTalker/venv/lib/python3.8/site-packages/TTS/api.py", line 385, in load_tts_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(
  File "/home/jiahuaw/test/SadTalker/SadTalker/venv/lib/python3.8/site-packages/TTS/api.py", line 348, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "/home/jiahuaw/test/SadTalker/SadTalker/venv/lib/python3.8/site-packages/TTS/utils/manage.py", line 309, in download_model
    output_model_path, output_config_path = self._find_files(output_path)
  File "/home/jiahuaw/test/SadTalker/SadTalker/venv/lib/python3.8/site-packages/TTS/utils/manage.py", line 332, in _find_files
    raise ValueError(" [!] Model file not found in the output path")
ValueError:  [!] Model file not found in the output path
运行webui.sh报错信息

**Comment by venxzw** [comment]
@SuperGoodGame Have you solved this problem?

**Comment by rifkathowekak** [comment]
删除tts_models--multilingual--multi-dataset--your_tts文件夹 让他重新下载

**Comment by SuperGoodGame** [comment]
> 删除tts_models--multilingual--multi-dataset--your_tts文件夹 让他重新下载

请问这个文件夹位置在哪里，或者能分享一下你的路径吗

**Comment by venxzw** [comment]
@rifkathowekak you can search this in your computer.

**Comment by ixp9891** [comment]
rm -rf /root/.local/share/tts/tts_models--multilingual--multi-dataset--your_tts 
然后重新执行 python app_sadtalker.py ,会重新下载
