### ISSUE TITLE
AUTO1111`s WebUI dev branch launch error

### ISSUE THREAD

**Issue by rltgjqmcpgjadyd** [OpenTalker/SadTalker#546]
webui dev branch 57e8a11d17a6646fdf551320f5f714fba752987a

here`s console log

*** Error executing callback ui_tabs_callback for J:\SDWebUI\extensions\SadTalker\scripts\extension.py
    Traceback (most recent call last):
      File "J:\SDWebUI\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "J:\SDWebUI\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
      File "J:\SDWebUI/extensions/SadTalker\app_sadtalker.py", line 3, in <module>
        from src.gradio_demo import SadTalker
      File "J:\SDWebUI/extensions/SadTalker\src\gradio_demo.py", line 6, in <module>
        from src.generate_batch import get_data
      File "J:\SDWebUI/extensions/SadTalker\src\generate_batch.py", line 8, in <module>
        import src.utils.audio as audio
      File "J:\SDWebUI/extensions/SadTalker\src\utils\audio.py", line 1, in <module>
        import librosa
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
        ^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\SDWebUI\venv\Lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
              ^^^^^^^^^^
      File "J:\SDWebUI\venv\Lib\site-packages\numpy\__init__.py", line 305, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

---

same error at sd-wav2lip-uhq https://github.com/numz/sd-wav2lip-uhq/issues/7

**Comment by quangdat2401** [comment]
I have same error when trying to run Sadtalker on Forge:

*** Error executing callback ui_tabs_callback for D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\extensions\SadTalker\scripts\extension.py
    Traceback (most recent call last):
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\modules\script_callbacks.py", line 183, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\extensions\SadTalker\app_sadtalker.py", line 3, in <module>
        from src.gradio_demo import SadTalker
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\extensions\SadTalker\src\gradio_demo.py", line 6, in <module>
        from src.generate_batch import get_data
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\extensions\SadTalker\src\generate_batch.py", line 8, in <module>
        import src.utils.audio as audio
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\extensions\SadTalker\src\utils\audio.py", line 1, in <module>
        import librosa
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\venv\Lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\venv\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
        ^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\venv\Lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
              ^^^^^^^^^^
      File "D:\Stable-diffusion\Forge\stable-diffusion-webui-forge\venv\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
