### ISSUE TITLE
都是按照步骤来装得，这是什么原因，有什么方法解决？

### ISSUE THREAD

**Issue by scetion** [OpenTalker/SadTalker#547]
To create a public link, set `share=True` in `launch()`.
Startup time: 18.5s (load scripts: 16.2s, create ui: 1.5s, gradio launch: 0.3s, app_started_callback: 0.4s).
using safetensor as default
{'checkpoint': 'D:\\sd-webui-aki-v4.2\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_512.safetensors', 'dir_of_BFM_fitting': 'D:\\sd-webui-aki-v4.2/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'D:\\sd-webui-aki-v4.2/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'D:\\sd-webui-aki-v4.2/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'D:\\sd-webui-aki-v4.2\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'D:\\sd-webui-aki-v4.2/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\ADMINI~1\AppData\Local\Temp\gradio\tmpx_dpepj0.png
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (512, 513) to (512, 528) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
'ffmpeg' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.2\python\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'f648a95a-c0de-4fce-8a04-acb056a0e9a3.mp4' -> './results/5f548acf-4c8a-42dc-afd8-776b3e529e4f\\tmpx_dpepj0##8月5日-0-100.mp4'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4.2/extensions/SadTalker\src\gradio_demo.py", line 139, in test
  File "D:\sd-webui-aki-v4.2/extensions/SadTalker\src\facerender\animate.py", line 222, in generate
    video_name_full = x['video_name']  + '_full.mp4'
  File "D:\sd-webui-aki-v4.2/extensions/SadTalker\src\utils\videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "D:\sd-webui-aki-v4.2\python\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "D:\sd-webui-aki-v4.2\python\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\sd-webui-aki-v4.2\python\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'f648a95a-c0de-4fce-8a04-acb056a0e9a3.mp4'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by deerestFarther** [comment]
The ffmpeg caused the issue. You can find the result .mp4 file at YOUR_SD_DIR/results/5f548acf-4c8a-42dc-afd8-776b3e529e4f\tmpx_dpepj0##8月5日-0-100.mp4
