### ISSUE TITLE
SadTalker showing this when ( generate ) its show erorr 

### ISSUE THREAD

**Issue by TestTime3000** [OpenTalker/SadTalker#554]
Already up to date.
venv folder already exists, skipping creation...
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: bd5b64af17ec1d5f54b35f91fdf985ff72233cc6
Installing requirements for SadTalker WebUI (may take longer time in first time)
Launching SadTalker Web UI
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
C:\Users\machi\AppData\Local\Temp\gradio\5a20c41c44cf7e9d24713c5ebe0b0a619cbd01a8\image.png
False None
Traceback (most recent call last):
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1392, in process_api    result = await self.call_function(
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\machi\Documents\SadTalker\SadTalker\venv\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\machi\Documents\SadTalker\SadTalker\src\gradio_demo.py", line 81, in test
    assert use_ref_video == True and ref_info == 'all'
AssertionError

**Comment by vincentsong** [comment]
Same issue

**Comment by blvvlb** [comment]
I have the same issue. Have you resolved it? thx

**Comment by leito711** [comment]
same

**Comment by Dannysdable** [comment]
same

**Comment by whoisterencelee** [comment]
I was able to solved this by doing the following:
1) use the dev branch with 'git checkout dev' in the sadtalker extension directory extensions\SadTalker
2) in same directory rename file app.py to app_sadtalker.py
3) edit extensions\SadTalker\scripts\extensions.py    line 172:     from app_sadtalker import sadtalker_demo  
4) edit extensions\SadTalker\src\utils\preprocessor.py line  line 101:     trans_params = np.array([w0, h0, s, t[0], t[1]], dtype=object)

As I understood, the dev branch has some new UI settings which sets the use_ref_video and ref_info variables, so you need move to the dev branch to work with the new code.  Alternatively you can also wait for the new release as they move more dev to master.
