### ISSUE TITLE
sd里面安装的SadTalker插件，点击生成后直接error了..

### ISSUE THREAD

**Issue by RomaYang** [OpenTalker/SadTalker#559]
Traceback (most recent call last):
  File "/Users/lixueyang/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/lixueyang/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/lixueyang/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/lixueyang/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1848, in preprocess
    return self._format_image(im)
  File "/Users/lixueyang/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
  File "/Users/lixueyang/stable-diffusion-webui/modules/ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/94/ky93r6ss51d5v3kxp930td2w0000gn/T/gradio/tmpo0p629g9.png'

**Comment by RomaYang** [comment]
@vinthony 辛苦帮忙看下

**Comment by RomaYang** [comment]
> 请问一下你是怎么解决的？

直接去报错路径下，把文件补全就好了，缺了个gradio文件

**Comment by KangolHsu** [comment]
缺了个gradio文件夹目录，在报错路径下创建一个gradio目录就行了
