### ISSUE TITLE
Issue with https://hub.docker.com/r/wawa9000/sadtalker

### ISSUE THREAD

**Issue by nitinmukesh** [OpenTalker/SadTalker#561]
Hello,

I have setup and installed docker / image.
When I try to run it comes up with following error

`
2023-08-10 14:02:55 Traceback (most recent call last):
2023-08-10 14:02:55   File "inference.py", line 131, in <module>
2023-08-10 14:02:55     main(args)
2023-08-10 14:02:55   File "inference.py", line 48, in main
2023-08-10 14:02:55     preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
2023-08-10 14:02:55   File "/app/SadTalker/src/utils/preprocess.py", line 46, in __init__
2023-08-10 14:02:55     self.kp_extractor = KeypointExtractor()
2023-08-10 14:02:55   File "/app/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
2023-08-10 14:02:55     self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)   
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/face_alignment/api.py", line 77, in __init__
2023-08-10 14:02:55     self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 31, in __init__
2023-08-10 14:02:55     self.face_detector.to(device)
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
2023-08-10 14:02:55     return self._apply(convert)
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
2023-08-10 14:02:55     module._apply(fn)
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
2023-08-10 14:02:55     param_applied = fn(param)
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
2023-08-10 14:02:55     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2023-08-10 14:02:55   File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
2023-08-10 14:02:55     torch._C._cuda_init()
2023-08-10 14:02:55 RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2023-08-10 14:02:55 ./checkpoints/epoch_20.pth
`

I checked the following works fine

`
C:\>pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
Looking in indexes: https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch in c:\python310\lib\site-packages (2.0.1+cu117)
Requirement already satisfied: torchvision in c:\python310\lib\site-packages (0.15.2+cu117)
Requirement already satisfied: torchaudio in c:\python310\lib\site-packages (2.0.2+cu117)
Requirement already satisfied: filelock in c:\python310\lib\site-packages (from torch) (3.9.0)
Requirement already satisfied: typing-extensions in c:\python310\lib\site-packages (from torch) (4.4.0)
Requirement already satisfied: sympy in c:\python310\lib\site-packages (from torch) (1.11.1)
Requirement already satisfied: networkx in c:\python310\lib\site-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in c:\python310\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: numpy in c:\python310\lib\site-packages (from torchvision) (1.24.1)
Requirement already satisfied: requests in c:\python310\lib\site-packages (from torchvision) (2.28.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\python310\lib\site-packages (from torchvision) (9.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python310\lib\site-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\python310\lib\site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python310\lib\site-packages (from requests->torchvision) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in c:\python310\lib\site-packages (from sympy->torch) (1.2.1)

C:\>pip3 install numpy
Requirement already satisfied: numpy in c:\python310\lib\site-packages (1.24.1)

C:\>python -c "import torch; print(torch.rand(2,3).cuda())"
tensor([[0.7083, 0.7132, 0.3501],
        [0.1955, 0.3809, 0.1455]], device='cuda:0')

C:\>python -c "import torch; print(torch.cuda.device_count())"
1
`

Now no idea what else should I try

**Comment by drvpn** [comment]
The error you are getting are saying that the python cannot detect a Nvidia GPU.  Do you have a Nvidia video card installed?  Have you installed the Nvidia drivers for it?
