### ISSUE TITLE
生成视频报错

### ISSUE THREAD

**Issue by pzc163** [OpenTalker/SadTalker#568]
使用秋叶的启动器安装sadtalker插件然后下载模型后，生成视频报错
To create a public link, set `share=True` in `launch()`.
Startup time: 7.4s (launcher: 1.7s, import torch: 1.7s, import gradio: 0.5s, setup paths: 0.4s, other imports: 0.5s, load scripts: 1.0s, create ui: 1.3s, gradio launch: 0.2s).
Applying attention optimization: xformers... done.
Model loaded in 3.5s (load weights from disk: 0.3s, create model: 0.4s, apply weights to model: 0.9s, apply half(): 0.7s, move model to device: 0.9s, calculate empty prompt: 0.1s).
Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "D:\stable diffusion\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PS\\AppData\\Local\\Temp\\gradio\\tmpi68s_xuf.png'
![image](https://github.com/OpenTalker/SadTalker/assets/105222039/a6177c78-a0ec-4670-b723-59cb51602b83)
ffmpeg已经安装并且添加到了环境变量
![image](https://github.com/OpenTalker/SadTalker/assets/105222039/e1591260-ed9c-4f3f-9bac-60abfbc19ab5)

**Comment by hylarucoder** [comment]
有一定可能性是要重启一下. 环境变量才能生效.
