### ISSUE TITLE
How to slove this error:RuntimeError: unexpected EOF, expected 23099 more bytes

### ISSUE THREAD

**Issue by linxiang4200** [OpenTalker/SadTalker#576]
hello, thanks your great work!
when I run demo in webui , i still got this error:

using safetensor as default
{'checkpoint': '/home/work/stable-diffusion-webui/models/SadTalker/SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': '/home/work/stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': '/home/work/stable-diffusion-webui/extensions/SadTalker/src/config/auido2pose.yaml', 'audio2exp_yaml_path': '/home/work/stable-diffusion-webui/extensions/SadTalker/src/config/auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': '/home/work/stable-diffusion-webui/models/SadTalker/mapping_00229-model.pth.tar', 'facerender_yaml': '/home/work/stable-diffusion-webui/extensions/SadTalker/src/config/facerender.yaml'}
Traceback (most recent call last):
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/work/stable-diffusion-webui/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/home/work/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 50, in test
    self.preprocess_model = CropAndExtract(self.sadtalker_paths, self.device)
  File "/home/work/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 49, in __init__
    self.propress = Preprocesser(device)
  File "/home/work/stable-diffusion-webui/extensions/SadTalker/src/utils/croper.py", line 21, in __init__
    self.predictor = KeypointExtractor(device)
  File "/home/work/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos_safe.py", line 46, in __init__
    self.det_net = init_detection_model('retinaface_resnet50', half=False,device=device, model_rootpath=root_path)
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/facexlib/detection/__init__.py", line 22, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/home/work/stable-diffusion-webui/modules/safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/home/work/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/work/diffuser-env/python/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 23099 more bytes. The file might be corrupted.

I have tried to redownload both GFPGAN and the checkpoint, placing them in the 'stable-diffusion-webui/extensions/SadTalker/gfpgan/weights/' and 'stable-diffusion-webui/models/SadTalker/' directories, respectively. However, the error still persists. I hope you could take a look at this issue for me. Thank you~

**Comment by linxiang4200** [comment]
is worked for Command Line "python3 inference.py --driven_audio xxxx"   , but not work for stable-diffusion-webui extension ,  strange...

**Comment by SzhLzj** [comment]
你需要将四个文件放入 stable-diffusion-webui/models/SadTalker/checkpoints 中，而不是stable-diffusion-webui/models/SadTalker/
