### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by SLajuwomi** [OpenTalker/SadTalker#597]
After running C:\Users\samst\SadTalker\webui.bat

Traceback (most recent call last):
  File "C:\Users\samst\SadTalker\Launcher.py", line 199, in <module>
    start()
  File "C:\Users\samst\SadTalker\Launcher.py", line 192, in start
    from app import sadtalker_demo
  File "C:\Users\samst\SadTalker\app.py", line 3, in <module>
    from src.gradio_demo import SadTalker
  File "C:\Users\samst\SadTalker\src\gradio_demo.py", line 3, in <module>
    from src.utils.preprocess import CropAndExtract
  File "C:\Users\samst\SadTalker\src\utils\preprocess.py", line 2, in <module>
    import cv2, os, sys, torch
  File "C:\Users\samst\SadTalker\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\samst\SadTalker\venv\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\samst\SadTalker\venv\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\samst\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\samst\SadTalker\venv\lib\site-packages\cv2\typing\__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable

Launch unsuccessful. Exiting.
Press any key to continue . . .

**Comment by Ninulz** [comment]
Which  Python versions are you using bro

**Comment by Mohamed2519** [comment]
Does anyone find the solution?
