### ISSUE TITLE
face alignment error ?

### ISSUE THREAD

**Issue by yangboz** [OpenTalker/SadTalker#613]
while inferencing ,it throws:
```
(py39) yangboz@192 SadTalker % python inference.py  --driven_audio blb.wav \
                    --source_image  examples/source_image/people_0.png \
                    --enhancer gfpgan
./checkpoints/epoch_20.pth
Traceback (most recent call last):
  File "/Users/yangboz/git/SadTalker/inference.py", line 158, in <module>
    main(args)
  File "/Users/yangboz/git/SadTalker/inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/Users/yangboz/git/SadTalker/src/utils/preprocess.py", line 52, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/Users/yangboz/git/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, 
  File "/Users/yangboz/anaconda3/envs/py39/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
```

any idea?

**Comment by yangboz** [comment]
even with default parameters, still

```
(py39) yangboz@192 SadTalker % python inference.py                          
./checkpoints/epoch_20.pth
Traceback (most recent call last):
  File "/Users/yangboz/git/SadTalker/inference.py", line 158, in <module>
    main(args)
  File "/Users/yangboz/git/SadTalker/inference.py", line 55, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/Users/yangboz/git/SadTalker/src/utils/preprocess.py", line 52, in __init__
    self.kp_extractor = KeypointExtractor(device)
  File "/Users/yangboz/git/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, 
  File "/Users/yangboz/anaconda3/envs/py39/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
```

**Comment by zero-or-one** [comment]
@yangboz I had the same problem. Go to 
  File "/Users/yangboz/git/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
  and change face_alignment.LandmarksType._2D to face_alignment.LandmarksType.TWO_D
