### ISSUE TITLE
I built an api with flask, and called sad_talker.test() in the built method,  But there was an error reported！

### ISSUE THREAD

**Issue by Jackzxs** [OpenTalker/SadTalker#619]
the method of flask:
from flask import Flask, request, jsonify
from src import t2a
from src.gradio_demo import SadTalker
import gradio as gr
import datetime
from PIL import Image
import os
app = Flask(__name__)

@app.route('/generate', methods=['POST'])
async def generate_video():
    data = request.json

    checkpoint_path = 'checkpoints'
    config_path = 'src/config'

    sad_talker = SadTalker(checkpoint_path, config_path, lazy_load=True)

    # 提取请求数据
    source_image_path = data['source_image']
    driven_audio_path = data['driven_audio']
    preprocess_type = data['preprocess_type']
    is_still_mode = data['is_still_mode']
    enhancer = data['enhancer']
    batch_size = data['batch_size']
    size_of_image = data['size_of_image']
    pose_style = data['pose_style']

    # 读取图片
    source_image = Image.open(source_image_path)

    # 设置图片宽度为 512
    width = 512
    height = int(width * source_image.size[1] / source_image.size[0])  # 等比例计算高度
    resized_image = source_image.resize((width, height))

    # 生成以当前日期命名的文件名
    now = datetime.datetime.now()
    date_string = now.strftime("%Y-%m-%d_%H-%M-%S")
    new_filename = f"{date_string}.png"

    # 拼接保存路径
    save_folder = r"D:\reposity\SadTalker-main\audio"
    save_path = os.path.join(save_folder, new_filename)
    # 保存图片至当前目录
    resized_image.save(save_path)

    # 关闭 Image 对象（释放资源）
    resized_image.close()

    # 运行SadTalker算法
    output_video_path = await sad_talker.test(save_path, driven_audio_path, preprocess_type, is_still_mode, enhancer, batch_size, size_of_image, pose_style)

    return jsonify({
        'output_video': output_video_path
    })

the test  json data of using postman :
{
    "source_image":"./audio/baby_new.png",
    "driven_audio":"./audio/tmp.mp3",
    "preprocess_type":"crop",
    "is_still_mode":"False",
    "enhancer":"False",
    "batch_size":"1",
    "size_of_image":"256",
    "pose_style":"5"
}

the error message: 
 [2023-09-04 17:57:47,346] ERROR in app: Exception on /generate [POST]
Traceback (most recent call last):
  File "D:\reposity\SadTalker-main\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\reposity\SadTalker-main\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\reposity\SadTalker-main\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\reposity\SadTalker-main\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\reposity\SadTalker-main\venv\lib\site-packages\asgiref\sync.py", line 277, in __call__
    return call_result.result()
  File "D:\sofwareInstall\python3.10.6\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\sofwareInstall\python3.10.6\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\reposity\SadTalker-main\venv\lib\site-packages\asgiref\sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "D:\reposity\SadTalker-main\sadtalkerflask.py", line 55, in generate_video
    output_video_path = await sad_talker.test(save_path, driven_audio_path, preprocess_type, is_still_mode, enhancer, batch_size, size_of_image, pose_style)
  File "D:\reposity\SadTalker-main\src\gradio_demo.py", line 132, in test
    first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess, True, size)
  File "D:\reposity\SadTalker-main\src\utils\preprocess.py", line 122, in generate
    frames_pil = [Image.fromarray(cv2.resize(frame,(pic_size, pic_size))) for frame in x_full_frames]
  File "D:\reposity\SadTalker-main\src\utils\preprocess.py", line 122, in <listcomp>
    frames_pil = [Image.fromarray(cv2.resize(frame,(pic_size, pic_size))) for frame in x_full_frames]
cv2.error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type

192.168.12.59 - - [04/Sep/2023 17:57:47] "POST /generate HTTP/1.1" 500 -

Does anyone know how to solve it！！

**Comment by johndpope** [comment]
ask chatgpt

**Comment by Jackzxs** [comment]
thanks  I solve the problem,  the type of size_of_image must be integer

**Comment by tsw123678** [comment]
> 谢谢我解决了问题，size_of_image的类型必须是整数

can you share the whole project? I am doing similar work recently. thank you

**Comment by Jackzxs** [comment]
> > 谢谢我解决了问题，size_of_image的类型必须是整数
> 
> can you share the whole project? I am doing similar work recently. thank you

just add one python  file  in root  file that using flask  to create api .  coding as :
 
from flask import Flask, request, jsonify
from src import t2a
from src.gradio_demo import SadTalker
import base64
import gradio as gr
import datetime
from PIL import Image
import os
app = Flask(__name__)

@app.route('/generate', methods=['POST'])
async def generate_video():
    data = request.json

    checkpoint_path = 'checkpoints'
    config_path = 'src/config'

    sad_talker = SadTalker(checkpoint_path, config_path, lazy_load=True)

    # 提取请求数据
    source_image_path = data['source_image']
    driven_audio_path = data['driven_audio']
    preprocess_type = data['preprocess_type']
    is_still_mode = data['is_still_mode']
    enhancer = data['enhancer']
    batch_size = data['batch_size']
    size_of_image = data['size_of_image']
    pose_style = data['pose_style']

    # 运行SadTalker算法
    output_video_path = await sad_talker.test(source_image_path, driven_audio_path, preprocess_type, is_still_mode, enhancer, batch_size, size_of_image, pose_style)

    return jsonify({
        'output_video': output_video_path
    })


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8910)

then you can run that file, and  access ip:8910 to test it

**Comment by tsw123678** [comment]
thanks for your code，wish you happiness发自我的 iPhone在 2023年9月11日，10:00，Jackzxs ***@***.***> 写道：﻿


谢谢我解决了问题，size_of_image的类型必须是整数

can you share the whole project? I am doing similar work recently. thank you

just add one python  file  in root  file that using flask  to create api .  coding as :
from flask import Flask, request, jsonify
from src import t2a
from src.gradio_demo import SadTalker
import base64
import gradio as gr
import datetime
from PIL import Image
import os
app = Flask(name)
@app.route('/generate', methods=['POST'])
async def generate_video():
data = request.json
checkpoint_path = 'checkpoints'
config_path = 'src/config'

sad_talker = SadTalker(checkpoint_path, config_path, lazy_load=True)

# 提取请求数据
source_image_path = data['source_image']
driven_audio_path = data['driven_audio']
preprocess_type = data['preprocess_type']
is_still_mode = data['is_still_mode']
enhancer = data['enhancer']
batch_size = data['batch_size']
size_of_image = data['size_of_image']
pose_style = data['pose_style']

# 运行SadTalker算法
output_video_path = await sad_talker.test(source_image_path, driven_audio_path, preprocess_type, is_still_mode, enhancer, batch_size, size_of_image, pose_style)

return jsonify({
    'output_video': output_video_path
})

if name == 'main':
app.run(host='0.0.0.0', port=8910)
then you can run that file, and  access ip:8910 to test it

**Comment by tsw123678** [comment]
i have another question.
in the code:from src import t2a
what's the meaning of t2a.
my file does not include it


yy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenTalker/SadTalker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 上午10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenTalker/SadTalker] I built an api with flask, and called sad_talker.test() in the built method,  But there was an error reported！ (Issue #619)





   
谢谢我解决了问题，size_of_image的类型必须是整数
  
can you share the whole project? I am doing similar work recently. thank you
  
just add one python  file  in root  file that using flask  to create api .  coding as :
 
from flask import Flask, request, jsonify
 from src import t2a
 from src.gradio_demo import SadTalker
 import base64
 import gradio as gr
 import datetime
 from PIL import Image
 import os
 app = Flask(name)
 
@app.route('/generate', methods=['POST'])
 async def generate_video():
 data = request.json
 checkpoint_path = 'checkpoints' config_path = 'src/config' sad_talker = SadTalker(checkpoint_path, config_path, lazy_load=True) # 提取请求数据 source_image_path = data['source_image'] driven_audio_path = data['driven_audio'] preprocess_type = data['preprocess_type'] is_still_mode = data['is_still_mode'] enhancer = data['enhancer'] batch_size = data['batch_size'] size_of_image = data['size_of_image'] pose_style = data['pose_style'] # 运行SadTalker算法 output_video_path = await sad_talker.test(source_image_path, driven_audio_path, preprocess_type, is_still_mode, enhancer, batch_size, size_of_image, pose_style) return jsonify({     'output_video': output_video_path })  
if name == 'main':
 app.run(host='0.0.0.0', port=8910)
 
then you can run that file, and  access ip:8910 to test it

**Comment by Jackzxs** [comment]
> i have another question. in the code:from src import t2a what's the meaning of t2a. my file does not include it yy ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "OpenTalker/SadTalker" ***@***.***&gt;; 发送时间:&nbsp;2023年9月11日(星期一) 上午10:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [OpenTalker/SadTalker] I built an api with flask, and called sad_talker.test() in the built method, But there was an error reported！ (Issue #619) 谢谢我解决了问题，size_of_image的类型必须是整数 can you share the whole project? I am doing similar work recently. thank you just add one python file in root file that using flask to create api . coding as : from flask import Flask, request, jsonify from src import t2a from src.gradio_demo import SadTalker import base64 import gradio as gr import datetime from PIL import Image import os app = Flask(name) @app.route('/generate', methods=['POST']) async def generate_video(): data = request.json checkpoint_path = 'checkpoints' config_path = 'src/config' sad_talker = SadTalker(checkpoint_path, config_path, lazy_load=True) # 提取请求数据 source_image_path = data['source_image'] driven_audio_path = data['driven_audio'] preprocess_type = data['preprocess_type'] is_still_mode = data['is_still_mode'] enhancer = data['enhancer'] batch_size = data['batch_size'] size_of_image = data['size_of_image'] pose_style = data['pose_style'] # 运行SadTalker算法 output_video_path = await sad_talker.test(source_image_path, driven_audio_path, preprocess_type, is_still_mode, enhancer, batch_size, size_of_image, pose_style) return jsonify({ 'output_video': output_video_path }) if name == 'main': app.run(host='0.0.0.0', port=8910) then you can run that file, and access ip:8910 to test it — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

you can ignore it, If you want to convert voice to text，
You can refer to this： https://github.com/OpenTalker/SadTalker/discussions/569#discussion-5519136
