### ISSUE TITLE
I downgraded the 1.35.5 version，help me。

### ISSUE THREAD

**Issue by PANLI77** [OpenTalker/SadTalker#627]
*** Error executing callback ui_tabs_callback for E:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
    Traceback (most recent call last):
      File "E:\AI\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "E:\AI\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
      File "E:\AI\stable-diffusion-webui/extensions/SadTalker\app_sadtalker.py", line 3, in <module>
        from src.gradio_demo import SadTalker
      File "E:\AI\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 6, in <module>
        from src.generate_batch import get_data
      File "E:\AI\stable-diffusion-webui/extensions/SadTalker\src\generate_batch.py", line 8, in <module>
        import src.utils.audio as audio
      File "E:\AI\stable-diffusion-webui/extensions/SadTalker\src\utils\audio.py", line 1, in <module>
        import librosa
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
        from .convert import *  # pylint: disable=wildcard-import
        ^^^^^^^^^^^^^^^^^^^^^^
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
        from . import notation
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
        from ..util.exceptions import ParameterError
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\librosa\util\__init__.py", line 83, in <module>
        from .utils import *  # pylint: disable=wildcard-import
        ^^^^^^^^^^^^^^^^^^^^
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\librosa\util\utils.py", line 10, in <module>
        import numba
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\numba\__init__.py", line 55, in <module>
        _ensure_critical_deps()
      File "E:\AI\stable-diffusion-webui\venv\Lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
        raise ImportError("Numba needs NumPy 1.24 or less")
    ImportError: Numba needs NumPy 1.24 or less

**Comment by PANLI77** [comment]
Conflicts with sd-webui-roop, I turn off this extension and it works fine。
