### ISSUE TITLE
ImportError: cannot import name 'GFPGANer' from 'gfpgan' (unknown location)

### ISSUE THREAD

**Issue by lvsh2012** [OpenTalker/SadTalker#628]
**python inference.py --driven_audio test/test.wav --source_image test/zh.png --result_dir results> --still --preprocess full --enhancer gfpgan**

Traceback (most recent call last):
  File "D:\code\python\SadTalker\inference.py", line 10, in <module>
    from src.facerender.animate import AnimateFromCoeff
  File "D:\code\python\SadTalker\src\facerender\animate.py", line 23, in <module>
    from src.utils.face_enhancer import enhancer_generator_with_len, enhancer_list
  File "D:\code\python\SadTalker\src\utils\face_enhancer.py", line 4, in <module>
    from gfpgan import GFPGANer
**ImportError: cannot import name 'GFPGANer' from 'gfpgan' (unknown location)**

**Comment by lvsh2012** [comment]
win10 环境，使用以下命令

Install [Python 3.10.6](https://www.python.org/downloads/windows/), checking "Add Python to PATH".
Install [git](https://git-scm.com/download/win) manually (OR scoop install git via [scoop](https://scoop.sh/)).
Install ffmpeg, following [this instruction](https://www.wikihow.com/Install-FFmpeg-on-Windows) (OR using scoop install ffmpeg via [scoop](https://scoop.sh/)).
Download our SadTalker repository, for example by running git clone https://github.com/Winfredy/SadTalker.git.
Download the checkpoint and gfpgan [below↓](https://github.com/Winfredy/SadTalker#-2-download-trained-models).
Run start.bat from Windows Explorer as normal, non-administrator, user, a gradio WebUI demo will be started.

**Comment by zyj-2000** [comment]
pip install gfpgan
