### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'c983140c-5a50-426c-95bd-28458f4da610.mp4'

### ISSUE THREAD

**Issue by AIrtistry** [OpenTalker/SadTalker#630]
Hi,

<img width="1270" alt="Untitled" src="https://github.com/OpenTalker/SadTalker/assets/139043392/43960433-d741-46ba-a0e4-76705c20970d">

Get this error with a1111 extension, correctly installed and place the whole checkpoint folder into "..\Documents\Stable diffusion\stable-diffusion-webui\extensions\SadTalker\checkpoints"

Any solutions ? Thanks you

**Comment by AIrtistry** [comment]
fixed by installed ffmepg

**Comment by Rayy16** [comment]
excuse me，may i ask for module version of your `ffmepg` 

i install `ffmepg` module (1.4 version), but it still threw error as yours

<details><summary>details info</summary>

```sh

pip list | grep ffmpeg
ffmpeg                    1.4
imageio-ffmpeg            0.4.7
(sadtalker) ubuntu1@ubuntu1-VirtualBox:~/fintech_practices/pkg/SadTalker$ python inference.py --driven_audio ./sample/text.txt_1_qyztest.wav.wav --source_image ./sample/testPng.png --result_dir ./results --enhancer gfpgan
using safetensor as default
3DMM Extraction for source image
[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
landmark Det:: 100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.66s/it]
3DMM Extraction In Video:: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.23it/s]
mel:: 100%|█████████████████████████████████████████████████████████████████████████████████████| 484/484 [00:00<00:00, 139713.91it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:00<00:00, 63.51it/s]
Face Renderer:: 100%|█████████████████████████████████████████████████████████████████████████████| 242/242 [1:18:45<00:00, 19.53s/it]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 237) to (256, 240) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
sh: 1: ffmpeg: not found
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '63dc1e29-6c9e-4a00-8217-a44f79920415.mp4' -> './results/2023_10_30_13.03.37/testPng##text.txt_1_qyztest.wav.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 144, in <module>
    main(args)
  File "inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/home/ubuntu1/fintech_practices/pkg/SadTalker/src/facerender/animate.py", line 222, in generate
    save_video_with_watermark(path, new_audio_path, av_path, watermark= False)
  File "/home/ubuntu1/fintech_practices/pkg/SadTalker/src/utils/videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "/usr/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '63dc1e29-6c9e-4a00-8217-a44f79920415.mp4'
```

</details>

**Comment by AndreFCosta608** [comment]
sudo apt-get install ffmpeg
