### ISSUE TITLE
Output wav not found

### ISSUE THREAD

**Issue by epicstar7** [OpenTalker/SadTalker#631]
Hi, I'm getting this error, seems like the audio from the driving video is not correctly saved or can't be copied to the working directory or something.

Anybody know what to do?

ps. I'm running on Windows with the dev branch (git clone -b dev https://github.com/OpenTalker/SadTalker)

`
[in#0 @ 000001dd75a47400] Error opening input: No such file or directory
Error opening input file C:\Users\pc\AppData\Local\Temp\gradio\778f1299ca2d5da3e61164cc83acd1abbe7b20fd\input.
Error opening input files: No such file or directory
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.07it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.97it/s]
using ref video for genreation
3DMM Extraction for the reference video providing pose
landmark Det:: 100%|█████████████████████████████████████████████████████████████████| 134/134 [00:10<00:00, 13.29it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████| 134/134 [00:01<00:00, 69.70it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 134/134 [00:13<00:00,  9.74it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 255) to (256, 256) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
Traceback (most recent call last):
  File "C:\df\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\df\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\df\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\df\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\df\SadTalker\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\df\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\df\SadTalker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\df\SadTalker\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\df\SadTalker\src\gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "C:\df\SadTalker\src\facerender\animate.py", line 215, in generate
    sound = AudioSegment.from_file(audio_path)
  File "C:\df\SadTalker\venv\lib\site-packages\pydub\audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "C:\df\SadTalker\venv\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: './results/1d029e3b-0156-4b5c-8960-d47b2c178adf\\input.mp4.wav'
`

**Comment by dedkamaroz** [comment]
did you find a fix for this?
