### ISSUE TITLE
ValueError: Image data must be a sequence of ndimages

### ISSUE THREAD

**Issue by why-is-me** [OpenTalker/SadTalker#634]
I have used the latest version of SD webui (1.6) and the current latest SadTalker (0.0.2), and Ubantu22.04, Python 3.11.4 ，4060ti  but I still reported the following similar error：
Traceback (most recent call last):
  File "/opt/sd/extensions/SadTalker/src/facerender/animate.py", line 244, ingenerate
    imageio.mimsave(enhanced_path, enhanced_images_gen_with_len, fps=float(25))
  File "/usr/local/lib/python3.11/site-packages/imageio/v2.py", line 490, in mimwrite
    raise **ValueError("Image data must be a sequence of ndimages.")**
ValueError: Image data must be a sequence of ndimages.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1431,in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1103,in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33,in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py",line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py",line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/opt/sd/extensions/SadTalker/src/gradio_demo.py", line 139, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path,crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sd/extensions/SadTalker/src/facerender/animate.py", line 247, ingenerate
    enhanced_images_gen_with_len = enhancer_list(full_video_path, method=enhancer, bg_upsampler=background_enhancer)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sd/extensions/SadTalker/src/utils/face_enhancer.py", line 28, inenhancer_list
    return list(gen)
           ^^^^^^^^^
  File "/opt/sd/extensions/SadTalker/src/utils/face_enhancer.py", line 103, in enhancer_generator_no_len
    restorer = GFPGANer(
               ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gfpgan/utils.py", line 90, in__init__
    model_path = load_file_from_url(
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/sd/modules/gfpgan_model.py", line 86, in my_load_file_from_url
    return load_file_from_url_orig(**dict(kwargs, model_dir=model_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/basicsr/utils/download_util.py", line 98, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/usr/local/lib/python3.11/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by why-is-me** [comment]
Of course, I have already seen the same error someone made before, and I am not sure if my error is the same as his problem. The new version still has this error，  Here is the link to his question：
https://github.com/OpenTalker/SadTalker/issues/353

**Comment by why-is-me** [comment]
After I modified the image size, it solved the problem
