### ISSUE TITLE
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'

### ISSUE THREAD

**Issue by Mark-a-ops** [OpenTalker/SadTalker#636]
Some pictures are working fine, but this one:
![src5](https://github.com/OpenTalker/SadTalker/assets/20512379/2f375545-98d0-42ee-b85a-c6f6896258ec)

Error Message:
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 254) to (256, 256) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
The generated video is named /content/drive/MyDrive/files/output/2023_09_13_00.14.43/src5##1-boliqiu.mp4
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
seamlessClone::   0% 0/2622 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/SadTalker/inference.py", line 144, in <module>
    main(args)
  File "/content/SadTalker/inference.py", line 87, in main
    result = animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/content/SadTalker/src/facerender/animate.py", line 230, in generate
    paste_pic(path, pic_path, crop_info, new_audio_path, full_video_path, extended_crop= True if 'ext' in preprocess.lower() else False)
  File "/content/SadTalker/src/utils/paste_pic.py", line 63, in paste_pic
    gen_img = cv2.seamlessClone(p, full_img, mask, location, cv2.NORMAL_CLONE)
cv2.error: OpenCV(4.8.0) /io/opencv/modules/core/src/matrix.cpp:808: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

**Comment by viperyl** [comment]
modify the following file:
`./src/utils/paste_pic.py` 
from `out_tmp = cv2.VideoWriter(tmp_path, cv2.VideoWriter_fourcc(*'MP4V'), fps, (frame_w, frame_h))`
to `out_tmp = cv2.VideoWriter(tmp_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (frame_w, frame_h))`

this works in my case

**Comment by tnfsmith** [comment]
There is no error message after change MP4V to mp4v (lower characters)
