### ISSUE TITLE
Cannot run in cpu only mode via docker

### ISSUE THREAD

**Issue by risharde** [OpenTalker/SadTalker#660]
Hi, I'm getting the following error trying to run the standard docker (except I removed --gpus 'all' part since that causes an absolutely fail in execution) command for SadTalker
I do not have an nvidia gpu and would like to run it on the cpu. Any ideas if this can be fixed (or support for AMD GPUs?)

D:\ai_docker\sadtalker>docker run --rm -v D:\ai_docker\sadtalker:/host_dir wawa9000/sadtalker --driven_audio /host_dir/audio.wav --source_image /host_dir/photo.png --expression_scale 1.0 --cpu --still --result_dir /host_dir
./checkpoints/epoch_20.pth
Traceback (most recent call last):
  File "inference.py", line 131, in <module>
    main(args)
  File "inference.py", line 48, in main
    preprocess_model = CropAndExtract(path_of_lm_croper, path_of_net_recon_model, dir_of_BFM_fitting, device)
  File "/app/SadTalker/src/utils/preprocess.py", line 46, in __init__
    self.kp_extractor = KeypointExtractor()
  File "/app/SadTalker/src/face3d/extract_kp_videos.py", line 16, in __init__
    self.detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)
  File "/usr/local/lib/python3.8/site-packages/face_alignment/api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "/usr/local/lib/python3.8/site-packages/face_alignment/detection/sfd/sfd_detector.py", line 31, in __init__
    self.face_detector.to(device)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 927, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by risharde** [comment]
@vinthony tagged

**Comment by Maximus48p** [comment]
same issue..

**Comment by lincyang** [comment]
who can help us...
