### ISSUE TITLE
TTS cannot get installed in given environment

### ISSUE THREAD

**Issue by pk1762012** [OpenTalker/SadTalker#700]
pip install TTS

does not get the right version of transformers. The sadtalker app is also not loading due to package conflicts. 

python app_sadtalker.py
/home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "app_sadtalker.py", line 107, in <module>
    demo = sadtalker_demo()
  File "app_sadtalker.py", line 48, in sadtalker_demo
    from src.utils.text2speech import TTSTalker
  File "/home/pk/python_p/SadTalker/src/utils/text2speech.py", line 3, in <module>
    from TTS.api import TTS
ModuleNotFoundError: No module named 'TTS.api'

pip install xformers==0.0.20 triton==2.0.0 gradio_client==0.2.7
Requirement already satisfied: xformers==0.0.20 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (0.0.20)
Requirement already satisfied: triton==2.0.0 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (2.0.0)
Collecting gradio_client==0.2.7
  Using cached gradio_client-0.2.7-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: numpy in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from xformers==0.0.20) (1.23.4)
Requirement already satisfied: pyre-extensions==0.0.29 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from xformers==0.0.20) (0.0.29)
Collecting torch==2.0.1 (from xformers==0.0.20)
  Using cached torch-2.0.1-cp38-cp38-manylinux1_x86_64.whl (619.9 MB)
Requirement already satisfied: cmake in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from triton==2.0.0) (3.27.7)
Requirement already satisfied: filelock in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from triton==2.0.0) (3.13.1)
Requirement already satisfied: lit in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from triton==2.0.0) (17.0.4)
Requirement already satisfied: fsspec in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (2023.10.0)
Requirement already satisfied: httpx in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (0.25.1)
Requirement already satisfied: huggingface-hub>=0.13.0 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (0.17.3)
Requirement already satisfied: packaging in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (23.2)
Requirement already satisfied: requests in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (2.31.0)
Requirement already satisfied: typing-extensions in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (4.8.0)
Requirement already satisfied: websockets in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from gradio_client==0.2.7) (11.0.3)
Requirement already satisfied: typing-inspect in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from pyre-extensions==0.0.29->xformers==0.0.20) (0.9.0)
Requirement already satisfied: sympy in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (1.11.1)
Requirement already satisfied: networkx in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (3.1)
Requirement already satisfied: jinja2 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from torch==2.0.1->xformers==0.0.20) (11.7.91)
Requirement already satisfied: setuptools in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1->xformers==0.0.20) (68.0.0)
Requirement already satisfied: wheel in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1->xformers==0.0.20) (0.41.2)
Requirement already satisfied: tqdm>=4.42.1 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from huggingface-hub>=0.13.0->gradio_client==0.2.7) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from huggingface-hub>=0.13.0->gradio_client==0.2.7) (6.0.1)
Requirement already satisfied: anyio in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from httpx->gradio_client==0.2.7) (3.7.1)
Requirement already satisfied: certifi in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from httpx->gradio_client==0.2.7) (2023.7.22)
Requirement already satisfied: httpcore in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from httpx->gradio_client==0.2.7) (1.0.1)
Requirement already satisfied: idna in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from httpx->gradio_client==0.2.7) (3.4)
Requirement already satisfied: sniffio in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from httpx->gradio_client==0.2.7) (1.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from requests->gradio_client==0.2.7) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from requests->gradio_client==0.2.7) (1.26.18)
Requirement already satisfied: exceptiongroup in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from anyio->httpx->gradio_client==0.2.7) (1.1.3)
Requirement already satisfied: h11<0.15,>=0.13 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from httpcore->httpx->gradio_client==0.2.7) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from jinja2->torch==2.0.1->xformers==0.0.20) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from sympy->torch==2.0.1->xformers==0.0.20) (1.3.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /home/pk/.conda/envs/sadtalker2/lib/python3.8/site-packages (from typing-inspect->pyre-extensions==0.0.29->xformers==0.0.20) (1.0.0)
Using cached gradio_client-0.2.7-py3-none-any.whl (288 kB)
Installing collected packages: gradio_client, torch
  Attempting uninstall: gradio_client
    Found existing installation: gradio_client 0.7.0
    Uninstalling gradio_client-0.7.0:
      Successfully uninstalled gradio_client-0.7.0
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1
    Uninstalling torch-1.12.1:
      Successfully uninstalled torch-1.12.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 3.40.0 requires gradio-client>=0.4.0, but you have gradio-client 0.2.7 which is incompatible.
torchaudio 0.12.1+cu113 requires torch==1.12.1, but you have torch 2.0.1 which is incompatible.
torchvision 0.13.1+cu113 requires torch==1.12.1, but you have torch 2.0.1 which is incompatible.

**Comment by Ziif** [comment]
I have the same problem. Have you solved it yet?

**Comment by pk1762012** [comment]
I think I downgraded the torch version

**Comment by pk1762012** [comment]
Python 3.9 or 3.10 env needed
Git clone the sadtalker repo - git clone https://github.com/OpenTalker/SadTalker.git
Cd SadTalker
conda create -n sadtalker python==3.9
Conda activate sadtalker
then - pip install TTS
conda install ffmpeg
pip install -r requirements.txt
pip install gradio=3.44.0
pip install scikit-learn==1.3.0
pip install scipy==1.11.2
pip install librosa==0.10.0 numpy==1.22.0
Check if all dependency issues resolved
python app_sadtalker.py

**Comment by pk1762012** [comment]
Despite this, there is no reference video in this installation. DO not know how to get this

**Comment by shareholdr** [comment]
Do this instead of hussle with the local version, full guide on how to get the Google colab variant to work here https://vm.tiktok.com/ZGeLNu2yq/
